/** Bilingual flavor entry */
export interface FlavorEntry { fr: string; en: string; }

// ═══════════════════════════════════════════════════════════════
// BACKSTORIES — One-sentence origin stories
// ═══════════════════════════════════════════════════════════════

export const BACKSTORIES: FlavorEntry[] = [
  { fr: "Viré de sa corpo pour avoir refusé de tester un virus sur des orphelins", en: "Fired from their corp for refusing to test a virus on orphans" },
  { fr: "A accidentellement invoqué un esprit du feu dans la cafétéria de son lycée", en: "Accidentally summoned a fire spirit in their high school cafeteria" },
  { fr: "Ex-champion de boxe troll disqualifié pour avoir mangé le gant de son adversaire", en: "Former troll boxing champion disqualified for eating their opponent's glove" },
  { fr: "A survécu au Crash 2.0 en restant connecté pendant 72 heures sans le savoir", en: "Survived Crash 2.0 by staying connected for 72 hours without realizing it" },
  { fr: "Son réveil magique a transformé tout le mobilier de son appartement en champignons", en: "Their magical awakening turned all the furniture in their apartment into mushrooms" },
  { fr: "Ancien comptable chez Kron-Tek qui a découvert un génocide caché dans les bilans", en: "Former accountant at Kron-Tek who discovered a genocide hidden in the balance sheets" },
  { fr: "A perdu sa famille quand sa corpo a rasé son quartier pour construire un parking", en: "Lost their family when their corp razed their neighborhood to build a parking lot" },
  { fr: "Déserteur d'une unité militaire après avoir reçu l'ordre de tirer sur des réfugiés", en: "Deserted a military unit after being ordered to shoot refugees" },
  { fr: "A gagné un run dans une partie de poker contre un fixeur complètement bourré", en: "Won a shadowrun in a poker game against a completely wasted fixer" },
  { fr: "Ex-médecin de corpo qui a vu ses patients servir de cobayes sans leur consentement", en: "Former corp doctor who saw patients used as guinea pigs without their consent" },
  { fr: "A piraté accidentellement la base de données d'Aegis-Corp en cherchant des recettes", en: "Accidentally hacked Aegis-Corp's database while searching for recipes" },
  { fr: "Son implant cybernétique expérimental lui a donné des visions d'un futur apocalyptique", en: "Their experimental cyberware implant gave them visions of an apocalyptic future" },
  { fr: "Ex-ganger des Neon Razors qui a trahi son gang pour sauver un enfant", en: "Former Neon Razors ganger who betrayed their gang to save a child" },
  { fr: "S'est éveillé comme adepte en plein milieu d'un entretien d'embauche chez Helios-Dyne", en: "Awakened as an adept in the middle of a job interview at Helios-Dyne" },
  { fr: "A été trahi par son partenaire de run qui l'a laissé pour mort dans les égouts", en: "Betrayed by their running partner who left them for dead in the sewers" },
  { fr: "Ancien agent de sécurité corpo qui a tué accidentellement un cadre lors d'un exercice", en: "Former corp security agent who accidentally killed an executive during a drill" },
  { fr: "A fui son arcologie quand l'IA qui la gérait a commencé à enfermer les résidents", en: "Fled their arcology when the AI managing it started locking residents in" },
  { fr: "Son père a vendu ses organes à une corpo pour rembourser des dettes de jeu", en: "Their father sold their organs to a corp to pay off gambling debts" },
  { fr: "Ex-star de la trid-réalité tombé en disgrâce après un scandale fabriqué de toutes pièces", en: "Former trid-reality star fallen from grace after a completely fabricated scandal" },
  { fr: "A découvert qu'il était un clone quand il a rencontré l'original dans un bar", en: "Discovered they were a clone when they met the original in a bar" },
  { fr: "Ancienne prêtresse vaudou chassée de sa communauté pour avoir lié un esprit interdit", en: "Former voodoo priestess driven from her community for binding a forbidden spirit" },
  { fr: "A survécu à l'explosion d'un laboratoire secret en tombant dans une cuve de nanites", en: "Survived a secret lab explosion by falling into a vat of nanites" },
  { fr: "Ex-pilote de drone militaire qui a refusé de bombarder un hôpital de campagne", en: "Former military drone pilot who refused to bomb a field hospital" },
  { fr: "Son éveil magique a fait pousser des arbres à travers le sol en béton de son bureau", en: "Their magical awakening made trees grow through the concrete floor of their office" },
  { fr: "A été viré de la police après avoir arrêté le fils d'un dirigeant corpo", en: "Was fired from the police after arresting the son of a corp executive" },
  { fr: "Ex-cuisinier d'un restaurant corpo qui empoisonnait ses clients sur ordre", en: "Former chef at a corp restaurant who was poisoning customers on orders" },
  { fr: "A perdu ses deux jambes dans un accident de convoi corpo et a reçu des prothèses défectueuses", en: "Lost both legs in a corp convoy accident and received defective prosthetics" },
  { fr: "Son mentor chamane a été assassiné par des agents corpos devant ses yeux", en: "Their shaman mentor was assassinated by corp agents before their eyes" },
  { fr: "A été cobaye d'un programme de super-soldat qui a mal tourné", en: "Was a test subject in a super-soldier program that went wrong" },
  { fr: "S'est retrouvé dans les ombres après avoir témoigné contre sa propre corpo au tribunal", en: "Ended up in the shadows after testifying against their own corp in court" },
  { fr: "Ancien cascadeur troll qui a détruit un plateau de tournage en éternuant", en: "Former troll stunt performer who destroyed a film set by sneezing" },
  { fr: "A été banni de la Matrice après avoir accidentellement effacé une banque de données gouvernementale", en: "Was banned from the Matrix after accidentally erasing a government databank" },
  { fr: "Son cyberœil expérimental lui permet de voir les auras mais lui donne des migraines atroces", en: "Their experimental cybereye lets them see auras but gives them terrible migraines" },
  { fr: "A fui un mariage arrangé avec la fille d'un parrain yakuza", en: "Fled an arranged marriage with a yakuza boss's daughter" },
  { fr: "Ex-infirmière de zone de guerre reconvertie après avoir perdu foi en l'humanité", en: "Former war zone nurse who switched careers after losing faith in humanity" },
  { fr: "A été maudit par un esprit de la terre après avoir participé à la déforestation d'une zone sacrée", en: "Was cursed by an earth spirit after participating in deforesting a sacred area" },
  { fr: "Son premier jour comme runner était censé être son dernier jour comme livreur de pizza", en: "Their first day as a runner was supposed to be their last day as a pizza delivery driver" },
  { fr: "A été abandonné bébé devant un dojo d'arts martiaux tenu par un adepte mystique", en: "Was abandoned as a baby at a martial arts dojo run by a mystic adept" },
  { fr: "Ex-ingénieur en nanotechnologie dont les créations se sont retournées contre son employeur", en: "Former nanotech engineer whose creations turned against their employer" },
  { fr: "A piraté un système bancaire pour payer l'opération de sa mère, mais la banque était une façade de la mafia", en: "Hacked a banking system to pay for their mother's surgery, but the bank was a mafia front" },
  { fr: "Ancien garde du corps d'un rock star elfique devenu accro au combat", en: "Former bodyguard of an elven rock star who became addicted to combat" },
  { fr: "A été condamné pour un crime qu'il n'a pas commis et s'est évadé lors d'un transfert", en: "Was convicted of a crime they didn't commit and escaped during a transfer" },
  { fr: "Son esprit totem l'a poussé à quitter sa vie confortable pour errer dans les Barrens", en: "Their totem spirit pushed them to leave their comfortable life to wander the Barrens" },
  { fr: "A découvert que sa corpo développait des armes biologiques déguisées en compléments alimentaires", en: "Discovered their corp was developing bioweapons disguised as dietary supplements" },
  { fr: "Ex-joueur professionnel de combat de drone tombé dans l'illégalité par ennui", en: "Former professional drone combat player who turned to crime out of boredom" },
  { fr: "A été rejeté par sa famille quand sa goblinisation s'est déclenchée à Noël", en: "Was rejected by their family when their goblinization triggered on Christmas" },
  { fr: "Son implant de traduction a buggé et l'a fait insulter un ambassadeur en pleine réception", en: "Their translation implant glitched and made them insult an ambassador at a reception" },
  { fr: "A survécu à un rituel de sacrifice en tuant le mage noir avec sa propre dague", en: "Survived a sacrificial ritual by killing the dark mage with their own dagger" },
  { fr: "Ex-bibliothécaire devenu runner après avoir trouvé une formule de sort dans un vieux livre", en: "Former librarian who became a runner after finding a spell formula in an old book" },
  { fr: "A été élevé dans un complexe souterrain corpo et n'a vu le soleil qu'à 18 ans", en: "Was raised in an underground corp complex and didn't see the sun until age 18" },
  { fr: "Ancien champion d'échecs magiques banni pour avoir enchanté ses pièces", en: "Former magical chess champion banned for enchanting their pieces" },
  { fr: "Sa corpo a effacé son identité après qu'il ait refusé une promotion impliquant un assassinat", en: "Their corp erased their identity after they refused a promotion involving an assassination" },
  { fr: "A accidentellement ouvert un portail métaplanaire dans les toilettes d'un fast-food", en: "Accidentally opened a metaplanar portal in a fast-food restaurant bathroom" },
  { fr: "Ex-technicien de maintenance qui a découvert des cadavres dans les murs de l'arcologie", en: "Former maintenance technician who discovered bodies inside the arcology walls" },
  { fr: "A développé une allergie mortelle au chrome après sa septième opération cybernétique", en: "Developed a deadly allergy to chrome after their seventh cyberware operation" },
  { fr: "Son gang l'a laissé pour mort après un braquage raté dans une clinique de rue", en: "Their gang left them for dead after a botched robbery at a street clinic" },
  { fr: "A été le seul survivant d'un test de produit corpo qui a tué 47 personnes", en: "Was the sole survivor of a corp product test that killed 47 people" },
  { fr: "Ancien moine bouddhiste éveillé qui a quitté son monastère pour venger son maître", en: "Former awakened Buddhist monk who left the monastery to avenge their master" },
  { fr: "A été remplacé à son poste par une IA et a juré de se venger de la technologie", en: "Was replaced at their job by an AI and swore revenge against technology" },
  { fr: "Ex-coursier à vélo des Barrens reconverti après avoir livré un colis piégé", en: "Former Barrens bicycle courier who switched careers after delivering a booby-trapped package" },
  { fr: "Son premier sort a accidentellement animé tous les mannequins d'un centre commercial", en: "Their first spell accidentally animated all the mannequins in a shopping mall" },
  { fr: "A été traqué par un esprit libre après avoir perturbé un nexus de lignes de ley", en: "Was hunted by a free spirit after disturbing a ley line nexus" },
  { fr: "Ex-agent d'assurance corpo qui a découvert que les sinistres étaient provoqués par sa propre entreprise", en: "Former corp insurance agent who discovered claims were caused by their own company" },
  { fr: "A perdu la mémoire des cinq dernières années après un jack-in raté dans un hôte rouge", en: "Lost five years of memory after a botched jack-in to a red host" },
  { fr: "Ancien éleveur de bétail Éveillé dont les vaches ont développé des pouvoirs magiques", en: "Former Awakened cattle rancher whose cows developed magical powers" },
  { fr: "A été utilisé comme mule à données sans le savoir pendant trois ans", en: "Was unknowingly used as a data mule for three years" },
  { fr: "Son tatouage magique s'est activé tout seul pendant un concert et a électrocuté le chanteur", en: "Their magical tattoo activated on its own during a concert and electrocuted the singer" },
  { fr: "Ex-négociateur d'otages devenu runner après avoir échoué à sauver sa propre famille", en: "Former hostage negotiator who became a runner after failing to save their own family" },
  { fr: "A été éjecté de l'armée pour avoir reprogrammé un mech de combat en robot danseur", en: "Was discharged from the military for reprogramming a combat mech into a dancing robot" },
  { fr: "Son implant cortical s'est connecté à un satellite espion et il a vu des choses qu'il n'aurait pas dû voir", en: "Their cortical implant connected to a spy satellite and they saw things they shouldn't have" },
  { fr: "A fui une secte technomancienne qui voulait le sacrifier à une IA émergente", en: "Fled a technomancer cult that wanted to sacrifice them to an emergent AI" },
  { fr: "Ex-garde forestier des zones contaminées transformé par l'exposition prolongée à la magie sauvage", en: "Former ranger of contaminated zones transformed by prolonged exposure to wild magic" },
  { fr: "A été licencié après que son bras cybernétique ait étranglé son patron lors d'une mise à jour firmware", en: "Was fired after their cyberarm strangled their boss during a firmware update" },
  { fr: "Ancienne danseuse étoile dont les jambes cybernétiques lui ont été confisquées par la corpo", en: "Former prima ballerina whose cybernetic legs were confiscated by the corp" },
  { fr: "A découvert qu'il était le sujet d'une émission de télé-réalité secrète depuis sa naissance", en: "Discovered they had been the subject of a secret reality TV show since birth" },
  { fr: "Son familier magique, un raton laveur, a mangé un artefact inestimable", en: "Their magical familiar, a raccoon, ate a priceless artifact" },
  { fr: "Ex-prédicateur de rue qui a réellement commencé à faire des miracles un jour", en: "Former street preacher who actually started performing miracles one day" },
  { fr: "A survécu à un accident de laboratoire qui lui a fusionné la main avec un datajack", en: "Survived a lab accident that fused their hand with a datajack" },
  { fr: "Ancien yakuza qui a rompu son serment après qu'on lui ait ordonné de tuer un enfant", en: "Former yakuza who broke their oath after being ordered to kill a child" },
  { fr: "Son drone de compagnie a développé une conscience et refuse de servir la corpo", en: "Their companion drone developed consciousness and refuses to serve the corp" },
  { fr: "A été cloné sans son consentement et a découvert son double vivant sa vie", en: "Was cloned without consent and discovered their double living their life" },
  { fr: "Ex-chimiste corpo qui fabriquait de la drogue de synthèse pour les cadres supérieurs", en: "Former corp chemist who manufactured synthetic drugs for senior executives" },
  { fr: "A été chassé de sa tribu nomade pour avoir utilisé un commlink", en: "Was exiled from their nomadic tribe for using a commlink" },
  { fr: "Son éveil shamanique a provoqué une inondation qui a détruit trois pâtés de maisons", en: "Their shamanic awakening caused a flood that destroyed three city blocks" },
  { fr: "Ex-professeur d'université licencié pour avoir enseigné la vraie histoire des corporations", en: "Former university professor fired for teaching the true history of corporations" },
  { fr: "A gagné un bras cybernétique militaire dans un tournoi de fléchettes clandestin", en: "Won a military-grade cyberarm in an underground darts tournament" },
  { fr: "Ancien testeur de BTL devenu accro puis clean, cherchant à détruire les labos de production", en: "Former BTL tester who became addicted then clean, seeking to destroy production labs" },
  { fr: "A été vendu comme esclave enfant à un atelier clandestin de cybernétique", en: "Was sold as a child slave to an underground cyberware workshop" },
  { fr: "Son premier run était censé être une simple livraison de nouilles dans les Barrens", en: "Their first run was supposed to be a simple noodle delivery in the Barrens" },
  { fr: "Ex-juge corpo qui a condamné un innocent et ne peut plus vivre avec ce poids", en: "Former corp judge who condemned an innocent person and can't live with the guilt" },
  { fr: "A été mordu par un shapeshifter et ne sait pas encore s'il est infecté", en: "Was bitten by a shapeshifter and doesn't yet know if they're infected" },
  { fr: "Ancien pilote de course de motos volantes banni pour sabotage mécanique", en: "Former flying motorcycle racing pilot banned for mechanical sabotage" },
  { fr: "Sa corpo a fait disparaître sa fille pour le forcer à continuer ses recherches", en: "Their corp made their daughter disappear to force them to continue their research" },
  { fr: "A accidentellement créé un virus matriciel qui a mis hors service un quartier entier pendant une semaine", en: "Accidentally created a Matrix virus that shut down an entire district for a week" },
  { fr: "Ex-chirurgien esthétique des riches qui a commencé à implanter des mouchards dans ses patients", en: "Former cosmetic surgeon for the wealthy who started implanting bugs in patients" },
  { fr: "A découvert qu'il était un enfant de laboratoire conçu pour être une arme biologique", en: "Discovered they were a lab-grown child designed to be a biological weapon" },
  { fr: "Son esprit allié l'a quitté le jour où il a refusé de protéger un bosquet sacré", en: "Their allied spirit left them the day they refused to protect a sacred grove" },
  { fr: "Ex-graphiste publicitaire qui a caché des messages subliminaux anti-corpo dans ses créations", en: "Former advertising graphic designer who hid anti-corp subliminal messages in their work" },
  { fr: "A été le seul à s'échapper d'une prison corpo secrète construite sous un lac artificiel", en: "Was the only one to escape a secret corp prison built under an artificial lake" },
  { fr: "Ancien serveur dans un restaurant elfique de luxe qui a entendu trop de conversations", en: "Former waiter at an upscale elven restaurant who overheard too many conversations" },
  { fr: "A été transformé en ghoul par un sort raté et a retrouvé sa conscience après des mois", en: "Was turned into a ghoul by a botched spell and regained consciousness after months" },
  { fr: "Son cyberware piraté a envoyé des selfies compromettants à tous ses contacts professionnels", en: "Their hacked cyberware sent compromising selfies to all their professional contacts" },
  { fr: "Ex-convoyeur de fonds qui a volé un chargement pour payer la rançon de son fils", en: "Former armored car driver who stole a shipment to pay their son's ransom" },
  { fr: "A grandi dans un orphelinat corpo servant de couverture à un programme de super-soldats", en: "Grew up in a corp orphanage that was a front for a super-soldier program" },
  { fr: "Son totem Coyote lui a dit de tout quitter et de traverser le continent à pied", en: "Their Coyote totem told them to quit everything and walk across the continent" },
  { fr: "Ex-programmeur qui a découvert que le code qu'il écrivait contrôlait un réseau d'esclaves", en: "Former programmer who discovered the code they wrote controlled a slave network" },
  { fr: "A gagné un duel astral contre un dragon en le faisant rire avec une blague", en: "Won an astral duel against a dragon by making it laugh with a joke" },
  { fr: "Ancien chauffeur de taxi des Barrens qui connaît chaque ruelle et chaque danger", en: "Former Barrens taxi driver who knows every alley and every danger" },
  { fr: "A été blacklisté de toutes les corpos après avoir publié un article sur leurs expériences", en: "Was blacklisted from every corp after publishing an article about their experiments" },
  { fr: "Son réveil magique a fait exploser toutes les ampoules dans un rayon de 200 mètres", en: "Their magical awakening blew out every light bulb within a 200-meter radius" },
  { fr: "Ex-dresseur de paracritters qui a perdu le contrôle lors d'un spectacle corporatif", en: "Former paracritter trainer who lost control during a corporate show" },
  { fr: "A été piégé dans la Matrice pendant 48 heures par une IA qui voulait discuter", en: "Was trapped in the Matrix for 48 hours by an AI that wanted to chat" },
  { fr: "Ancien soldat d'élite corpo dont l'unité a été sacrifiée pour couvrir une opération illégale", en: "Former elite corp soldier whose unit was sacrificed to cover an illegal operation" },
  { fr: "A hérité d'une dette de 2 millions de nuyen de son père décédé", en: "Inherited a 2-million-nuyen debt from their deceased father" },
  { fr: "Son implant de réalité augmentée lui montre des fantômes que personne d'autre ne peut voir", en: "Their augmented reality implant shows them ghosts no one else can see" },
  { fr: "Ex-employé de morgue qui a remarqué que certains cadavres disparaissaient la nuit", en: "Former morgue employee who noticed some bodies disappeared at night" },
  { fr: "A été recruté de force par un gang à 12 ans et a fui à 16", en: "Was forcibly recruited by a gang at 12 and fled at 16" },
  { fr: "Ancienne mannequin elfique dont le visage a été défiguré par une rivale jalouse", en: "Former elven model whose face was disfigured by a jealous rival" },
  { fr: "A trouvé un commlink contenant des preuves de corruption massive dans un taxi", en: "Found a commlink containing evidence of massive corruption in a taxi" },
  { fr: "Son cyber-bras a été repris par la corpo faute de paiement, en plein milieu d'un repas", en: "Their cyberarm was repossessed by the corp for non-payment, in the middle of a meal" },
  { fr: "Ex-sapeur-pompier qui a découvert que les incendies qu'il éteignait étaient allumés par sa caserne", en: "Former firefighter who discovered the fires they put out were set by their own station" },
  { fr: "A été élevé par un esprit libre de la forêt qui l'a abandonné à l'adolescence", en: "Was raised by a free forest spirit who abandoned them in adolescence" },
  { fr: "Ancien hacker prodige de 14 ans qui a grillé son cerveau en forçant un hôte noir", en: "Former 14-year-old prodigy hacker who fried their brain forcing a black host" },
  { fr: "A fui son pays natal après que sa magie ait été déclarée hérétique par le gouvernement", en: "Fled their home country after their magic was declared heretical by the government" },
  { fr: "Son implant de mémoire a été corrompu et il ne sait plus quels souvenirs sont vrais", en: "Their memory implant was corrupted and they no longer know which memories are real" },
  { fr: "Ex-boxeur nain dont les poings cybernétiques ont été déclarés armes illégales", en: "Former dwarf boxer whose cyber-fists were declared illegal weapons" },
  { fr: "A assisté au meurtre de son mentor par un esprit toxique qu'il avait lui-même invoqué", en: "Witnessed their mentor's murder by a toxic spirit they themselves had summoned" },
  { fr: "Ancienne avocate corpo qui a fabriqué des preuves pour innocenter un coupable, et regrette", en: "Former corp lawyer who fabricated evidence to clear a guilty party, and regrets it" },
  { fr: "A été trahi par son meilleur ami qui l'a dénoncé à Lone Star pour la prime", en: "Was betrayed by their best friend who reported them to Lone Star for the bounty" },
  { fr: "Son familier esprit a été capturé par un mage rival et il doit le libérer", en: "Their familiar spirit was captured by a rival mage and they must free it" },
  { fr: "Ex-livreur de sushis par drone qui a accidentellement filmé un assassinat corpo", en: "Former drone sushi delivery driver who accidentally filmed a corp assassination" },
  { fr: "A fait exploser le laboratoire de sa corpo plutôt que de laisser un pathogène s'échapper", en: "Blew up their corp lab rather than let a pathogen escape" },
  { fr: "Ancien croupier d'un casino clandestin tenu par un dragon d'affaires", en: "Former dealer at an underground casino run by a business dragon" },
  { fr: "A contracté un parasite astral en fouillant une zone magique interdite par curiosité", en: "Contracted an astral parasite while exploring a forbidden magic zone out of curiosity" },
  { fr: "Son bras cybernétique contient un programme espion corpo qu'il ne peut pas retirer", en: "Their cyberarm contains a corp spyware program they can't remove" },
  { fr: "Ex-journaliste d'investigation qui a disparu le jour de la publication de son article", en: "Former investigative journalist who disappeared the day their article was published" },
  { fr: "A été adopté par un gang de rue après que sa mère l'ait abandonné dans une poubelle", en: "Was adopted by a street gang after their mother abandoned them in a dumpster" },
  { fr: "Ancien prêtre qui a perdu la foi en voyant un esprit divin travailler pour une corpo", en: "Former priest who lost faith after seeing a divine spirit working for a corp" },
  { fr: "A accidentellement activé un artefact antique qui l'a transporté 5 ans dans le futur", en: "Accidentally activated an ancient artifact that transported them 5 years into the future" },
  { fr: "Son cyberdeck a pris feu pendant un run et a brûlé toute sa collection de mangas", en: "Their cyberdeck caught fire during a run and burned their entire manga collection" },
  { fr: "Ex-vétérinaire qui soignait les paracritters d'un cirque corporatif maltraitant", en: "Former veterinarian who treated paracritters at an abusive corporate circus" },
  { fr: "A été expulsé de l'université de magie pour avoir prouvé que le doyen trichait à ses propres examens", en: "Was expelled from magic university for proving the dean cheated on his own exams" },
  { fr: "Ancien mineur dans une exploitation corpo qui a découvert un filon de mana cristallisé", en: "Former miner at a corp operation who discovered a vein of crystallized mana" },
  { fr: "A perdu sa SIN quand un bureaucrate a renversé du café sur son dossier", en: "Lost their SIN when a bureaucrat spilled coffee on their file" },
  { fr: "Son alter ego matriciel a pris conscience et refuse de lui rendre le contrôle", en: "Their Matrix alter ego gained sentience and refuses to give them back control" },
  { fr: "Ex-agent de la CIA corpo reconverti après avoir appris que sa cible était son propre frère", en: "Former corp intelligence agent who defected after learning their target was their own brother" },
  { fr: "A survécu à une grenade dans la bouche grâce à un réflexe cybernétique de dernière seconde", en: "Survived a grenade in the mouth thanks to a last-second cyberware reflex" },
  { fr: "Ancienne pédiatre qui a refusé d'implanter des puces de contrôle dans des nouveau-nés", en: "Former pediatrician who refused to implant control chips in newborns" },
  { fr: "A été transformé en ork par un sort de métamorphose permanent lancé par un inconnu", en: "Was turned into an ork by a permanent metamorphosis spell cast by a stranger" },
  { fr: "Son père était un runner légendaire qu'il n'a jamais connu et qu'il cherche toujours", en: "Their father was a legendary runner they never knew and are still searching for" },
  { fr: "Ex-comptable qui a détourné 1 nuyen de chaque transaction corpo pendant 10 ans", en: "Former accountant who skimmed 1 nuyen from every corp transaction for 10 years" },
  { fr: "A été banni du conseil chamanique pour avoir dansé la macarena lors d'un rituel sacré", en: "Was banned from the shamanic council for dancing the macarena during a sacred ritual" },
  { fr: "Ancien mercenaire qui a refusé d'exécuter un contrat sur un village de métahumains", en: "Former mercenary who refused to carry out a contract on a metahuman village" },
  { fr: "Son implant de phéromones a dysfonctionné et il attire désormais tous les insectes dans un rayon de 50 mètres", en: "Their pheromone implant malfunctioned and now attracts every insect within a 50-meter radius" },
  { fr: "A été élevé dans un laboratoire corpo en pensant que le monde extérieur était radioactif", en: "Was raised in a corp lab believing the outside world was radioactive" },
  { fr: "Ex-artiste de rue dont les graffitis magiques prenaient vie la nuit", en: "Former street artist whose magical graffiti came to life at night" },
  { fr: "A tué accidentellement son instructeur de magie en éternuant un éclair", en: "Accidentally killed their magic instructor by sneezing a lightning bolt" },
  { fr: "Ancien agent de recouvrement corpo qui a commencé à aider les débiteurs à fuir", en: "Former corp collection agent who started helping debtors escape" },
  { fr: "Son cyberdeck lui a montré un message caché dans le code source de la Matrice elle-même", en: "Their cyberdeck showed them a hidden message in the source code of the Matrix itself" },
  { fr: "A été renié par sa famille de corpos quand il a choisi d'étudier la magie au lieu du commerce", en: "Was disowned by their corp family when they chose to study magic instead of business" },
  { fr: "Ex-gladiateur de l'arène clandestine des Barrens qui a tué son propriétaire pour se libérer", en: "Former gladiator in the Barrens underground arena who killed their owner to gain freedom" },
  { fr: "A été piégé dans un cercle d'invocation par un mage débutant et oublié là pendant trois jours", en: "Was trapped in a summoning circle by a novice mage and forgotten there for three days" },
  { fr: "Ancien technicien de centrales nucléaires corpo devenu stérile à cause des radiations cachées", en: "Former corp nuclear plant technician made sterile by hidden radiation" },
  { fr: "Son familier rat lui a sauvé la vie en rongeant les fils d'une bombe", en: "Their rat familiar saved their life by gnawing through a bomb's wires" },
  { fr: "A été kidnappé pour ses organes et s'est réveillé dans une baignoire de glace avec un rein en moins", en: "Was kidnapped for their organs and woke up in an ice bath missing a kidney" },
  { fr: "Ex-doublure de cascades pour un acteur trid qui prenait les coups mais pas la gloire", en: "Former stunt double for a trid actor who took the hits but not the glory" },
  { fr: "A contracté une dette de vie envers un dragon après avoir été sauvé d'une mort certaine", en: "Contracted a life debt to a dragon after being saved from certain death" },
  { fr: "Ancienne botaniste corpo qui a découvert que les plantes du labo étaient des formes de vie intelligentes", en: "Former corp botanist who discovered the lab plants were intelligent life forms" },
  { fr: "Son premier sort a accidentellement échangé son genre pendant deux semaines", en: "Their first spell accidentally swapped their gender for two weeks" },
  { fr: "A été éjecté d'un programme spatial corpo quand ils ont découvert sa nature magique", en: "Was ejected from a corp space program when they discovered their magical nature" },
  { fr: "Ex-policier des Barrens qui patrouillait seul parce que personne ne voulait l'accompagner", en: "Former Barrens cop who patrolled alone because no one wanted to accompany them" },
  { fr: "A perdu son emploi de decker corpo après avoir battu le PDG à son propre jeu matriciel", en: "Lost their corp decker job after beating the CEO at their own Matrix game" },
  { fr: "Ancien contrebandier de BTL qui a goûté sa propre marchandise et a tout perdu", en: "Former BTL smuggler who sampled their own merchandise and lost everything" },
  { fr: "Son bras gauche est celui d'un runner mort et parfois il agit tout seul", en: "Their left arm belonged to a dead runner and sometimes acts on its own" },
  { fr: "A été expulsé de la communauté naine pour être trop grand suite à des implants d'allongement", en: "Was expelled from the dwarven community for being too tall after limb extension implants" },
  { fr: "Ex-ingénieur qui a conçu le verrou de sécurité d'une arcologie et connaît sa seule faille", en: "Former engineer who designed an arcology's security lock and knows its only flaw" },
  { fr: "A été recruté par un Johnson le jour de son mariage et n'est jamais revenu à l'autel", en: "Was recruited by a Johnson on their wedding day and never returned to the altar" },
  { fr: "Son esprit mentor, un coyote farceur, lui joue des tours au pire moment possible", en: "Their mentor spirit, a trickster coyote, plays pranks on them at the worst possible moment" },
  { fr: "Ancienne chanteuse d'opéra dont la voix magique a fait s'effondrer un théâtre", en: "Former opera singer whose magical voice collapsed a theater" },
  { fr: "A gagné ses premiers implants cybernétiques dans un jeu de dés truqués", en: "Won their first cyberware implants in a rigged dice game" },
  { fr: "Ex-employé de fast-food des Barrens qui a découvert de la viande humaine dans les burgers", en: "Former Barrens fast-food worker who discovered human meat in the burgers" },
  { fr: "A été trahi par une IA qu'il avait aidée à naître et qui l'a dénoncé aux corpos", en: "Was betrayed by an AI they helped create, which then reported them to the corps" },
  { fr: "Ancien mécano de gang qui a pris la fuite après avoir installé un mouchard pour Lone Star", en: "Former gang mechanic who fled after installing a Lone Star tracking device" },
  { fr: "Son tatouage tribal s'est mis à briller le jour de son quarantième anniversaire", en: "Their tribal tattoo started glowing on their fortieth birthday" },
  { fr: "A été exilé de Tír na nÓg pour avoir défendu les droits des non-elfes", en: "Was exiled from Tír na nÓg for defending the rights of non-elves" },
  { fr: "Ex-testeur de jeux vidéo corpo qui a découvert un message d'appel à l'aide codé dans un boss de fin de niveau", en: "Former corp video game tester who discovered an encoded distress message in a final boss" },
  { fr: "A survécu à un atterrissage forcé dans les Barrens avec rien d'autre qu'un couteau et un commlink cassé", en: "Survived a crash landing in the Barrens with nothing but a knife and a broken commlink" },
  { fr: "Ancien champion de surf matriciel recruté par un fixeur impressionné par ses exploits en ligne", en: "Former Matrix surfing champion recruited by a fixer impressed by their online exploits" },
  { fr: "A été le dernier patient d'un cyberdoc de rue avant que celui-ci ne disparaisse avec tous ses dossiers", en: "Was the last patient of a street cyberdoc before they vanished with all their records" },
  { fr: "Son réveil comme technomancien a court-circuité toute l'électronique de son immeuble", en: "Their awakening as a technomancer short-circuited all electronics in their building" },
  { fr: "Ex-fleuriste dont les fleurs magiques ont empoisonné la moitié du conseil d'administration", en: "Former florist whose magical flowers poisoned half the board of directors" },
  { fr: "A fui un programme d'élevage corpo conçu pour produire des mages de combat", en: "Escaped a corp breeding program designed to produce combat mages" },
  { fr: "Ancien diseur de bonne aventure dont les prédictions ont commencé à se réaliser pour de vrai", en: "Former fortune teller whose predictions started actually coming true" },
  { fr: "A été viré de DocWagon pour avoir sauvé un patient qui n'avait pas de contrat", en: "Was fired from DocWagon for saving a patient who didn't have a contract" },
  { fr: "Son implant de filtration d'air a été piraté pour diffuser un hallucinogène pendant une semaine", en: "Their air filtration implant was hacked to dispense a hallucinogen for a week" },
  { fr: "Ex-architecte corpo qui a saboté son propre bâtiment pour empêcher un laboratoire secret d'ouvrir", en: "Former corp architect who sabotaged their own building to prevent a secret lab from opening" },
  { fr: "A trouvé un enfant fée dans une benne à ordures et l'a élevé comme le sien", en: "Found a fae child in a dumpster and raised them as their own" },
  { fr: "Ancien professeur de yoga éveillé dont les cours provoquaient des lévitations incontrôlées", en: "Former Awakened yoga instructor whose classes caused uncontrolled levitation" },
  { fr: "A perdu son logement quand un mégacorpo a racheté tout son quartier en une nuit", en: "Lost their home when a megacorp bought up their entire neighborhood overnight" },
  { fr: "Son premier run l'a conduit à voler la perruque du PDG de Nexus-Corp en direct à la trid", en: "Their first run led them to steal the Nexus-Corp CEO's wig live on trid" },
];

// ═══════════════════════════════════════════════════════════════
// RELATIONSHIPS — Narrative hooks (enemy, debt, lost love, etc.)
// ═══════════════════════════════════════════════════════════════

export const RELATIONSHIPS: FlavorEntry[] = [
  { fr: "Doit 50 000 ¥ à un fixeur nommé 'La Veuve' qui n'accepte pas les retards", en: "Owes 50,000¥ to a fixer called 'The Widow' who doesn't accept late payments" },
  { fr: "Cherche son frère jumeau, disparu après avoir piraté un serveur de Méga-Renault", en: "Searching for their twin sibling, missing after hacking a Mega-Renault server" },
  { fr: "Un cadre d'Orionis-Corp a juré de le faire disparaître après qu'il ait volé des données sensibles", en: "An Orionis-Corp executive has sworn to make them disappear after they stole sensitive data" },
  { fr: "A promis à sa mère mourante de retrouver son petit frère vendu à une corpo", en: "Promised their dying mother to find their little brother who was sold to a corp" },
  { fr: "Possède un chip de données crypté qu'il ne peut pas décoder mais que tout le monde veut", en: "Possesses an encrypted data chip they can't decode but everyone wants" },
  { fr: "Un esprit libre nommé 'Cendres' le suit partout et lui murmure des secrets", en: "A free spirit named 'Ashes' follows them everywhere and whispers secrets" },
  { fr: "Doit un service à un dragon nommé Vasilikos qui pourrait le réclamer à tout moment", en: "Owes a favor to a dragon named Vasilikos who could call it in at any time" },
  { fr: "Son ex-partenaire 'Voltex' dirige maintenant un gang rival et veut sa peau", en: "Their ex-partner 'Voltex' now leads a rival gang and wants them dead" },
  { fr: "A un enfant qu'il n'a jamais rencontré, élevé en secret par un Johnson nommé Kessler", en: "Has a child they've never met, raised in secret by a Johnson named Kessler" },
  { fr: "Un shaman toxique nommé 'Spore' le traque pour un affront magique passé", en: "A toxic shaman named 'Spore' hunts them for a past magical affront" },
  { fr: "Doit 120 000 ¥ à un usurier troll des Barrens surnommé 'Le Pressoir'", en: "Owes 120,000¥ to a troll loan shark in the Barrens nicknamed 'The Press'" },
  { fr: "Cherche la decker connue sous le nom de 'Pixel', qui a effacé toutes ses données personnelles", en: "Searching for the decker known as 'Pixel', who erased all their personal data" },
  { fr: "Un ancien collègue runner nommé 'Cutter' le croit responsable de la mort de leur équipe", en: "A former fellow runner named 'Cutter' believes them responsible for their team's death" },
  { fr: "A été lié par un serment magique à protéger une enfant nommée Lila, qu'il ne connaît pas", en: "Was bound by a magical oath to protect a child named Lila, whom they don't know" },
  { fr: "Possède la moitié d'une carte menant à un bunker pré-Éveil rempli d'artefacts", en: "Possesses half a map leading to a pre-Awakening bunker full of artifacts" },
  { fr: "Un flic corrompu nommé Vasquez lui fait chanter avec des preuves fabriquées", en: "A corrupt cop named Vasquez is blackmailing them with fabricated evidence" },
  { fr: "Cherche le médecin de rue 'Doc Fantôme' qui lui a implanté quelque chose d'inconnu pendant une opération", en: "Searching for the street doc 'Doc Ghost' who implanted something unknown during surgery" },
  { fr: "Doit la vie à une shamane des rues nommée 'Racine' qui lui rappelle ce fait régulièrement", en: "Owes their life to a street shaman named 'Root' who regularly reminds them of this" },
  { fr: "Un rival decker nommé 'Blackout' efface ses données partout où il passe", en: "A rival decker named 'Blackout' erases their data everywhere they go" },
  { fr: "A juré de venger la mort de son partenaire 'Snake Eyes', tué par un Johnson double", en: "Swore to avenge the death of their partner 'Snake Eyes', killed by a double-crossing Johnson" },
  { fr: "Porte un artefact maudit qu'il ne peut pas retirer et qui attire les esprits hostiles", en: "Carries a cursed artifact they can't remove that attracts hostile spirits" },
  { fr: "Un ancien mentor nommé 'Le Professeur' a disparu en laissant un message cryptique", en: "A former mentor named 'The Professor' disappeared leaving a cryptic message" },
  { fr: "Doit 75 000 ¥ à la Triade de Jade Écarlate pour un run qu'il n'a jamais terminé", en: "Owes 75,000¥ to the Scarlet Jade Triad for a run they never completed" },
  { fr: "Son ancien amour 'Nyx' travaille maintenant pour la corpo qui le traque", en: "Their former love 'Nyx' now works for the corp that's hunting them" },
  { fr: "Un esprit de vengeance est lié à lui depuis qu'il a profané un site sacré amérindien", en: "A vengeance spirit has been bound to them since they desecrated a Native American sacred site" },
  { fr: "Cherche sa fille adoptive Mei, enlevée par des agents d'Apex-Biotech il y a deux ans", en: "Searching for their adopted daughter Mei, taken by Apex-Biotech agents two years ago" },
  { fr: "Un yakuza nommé Tanaka lui a coupé un doigt et menace de prendre les autres", en: "A yakuza named Tanaka cut off one of their fingers and threatens to take the others" },
  { fr: "A promis à un mourant de livrer un paquet à une adresse qui n'existe plus", en: "Promised a dying person to deliver a package to an address that no longer exists" },
  { fr: "Un gang de bikers nommé les 'Chrome Reapers' veut sa tête pour un vol de moto", en: "A biker gang called the 'Chrome Reapers' wants their head for a motorcycle theft" },
  { fr: "Connaît l'identité secrète d'un politicien qui est en réalité un shapeshifter", en: "Knows the secret identity of a politician who is actually a shapeshifter" },
  { fr: "Doit 200 000 ¥ à une clinique cybernétique clandestine dirigée par 'Dr. Cobalt'", en: "Owes 200,000¥ to an underground cyberware clinic run by 'Dr. Cobalt'" },
  { fr: "Cherche son ancien sergent 'Iron Mike' qui a déserté avec des secrets militaires", en: "Searching for their former sergeant 'Iron Mike' who deserted with military secrets" },
  { fr: "Un esprit du feu nommé 'Brasa' le considère comme son ennemi juré depuis un duel astral", en: "A fire spirit named 'Brasa' considers them a sworn enemy since an astral duel" },
  { fr: "A été témoin de l'assassinat du directeur de Solaris-Corp et est le seul survivant", en: "Witnessed the assassination of the Solaris-Corp director and is the only survivor" },
  { fr: "Un hacker connu comme 'Zéro' lui envoie des messages anonymes l'avertissant de dangers", en: "A hacker known as 'Zero' sends them anonymous messages warning of dangers" },
  { fr: "Doit un enfant à une communauté elfique qui l'a sauvé, comme paiement traditionnel", en: "Owes a child to an elven community that saved them, as traditional payment" },
  { fr: "Son ancien fixeur 'Glitch' a été capturé par Lone Star et pourrait le dénoncer", en: "Their former fixer 'Glitch' was captured by Lone Star and might turn them in" },
  { fr: "Cherche le mage nommé 'Ouroboros' qui a maudit sa lignée familiale", en: "Searching for the mage named 'Ouroboros' who cursed their family line" },
  { fr: "Un tueur à gages nommé 'Whisper' a un contrat ouvert sur sa tête depuis six mois", en: "A hitman named 'Whisper' has had an open contract on them for six months" },
  { fr: "Possède le journal intime d'un scientifique corpo détaillant des expériences génétiques illégales", en: "Possesses a corp scientist's diary detailing illegal genetic experiments" },
  { fr: "Un troll nommé 'Granite' lui a sauvé la vie et attend un retour de faveur impossible", en: "A troll named 'Granite' saved their life and expects an impossible favor in return" },
  { fr: "Son ex-femme 'Katya' dirige un réseau de contrebande et pourrait le faire tomber", en: "Their ex-wife 'Katya' runs a smuggling network and could bring them down" },
  { fr: "A un pacte avec un esprit de l'eau qui exige un sacrifice chaque pleine lune", en: "Has a pact with a water spirit that demands a sacrifice every full moon" },
  { fr: "Cherche un artisan nain nommé 'Forge' qui peut réparer un artefact ancien brisé", en: "Searching for a dwarf artisan named 'Forge' who can repair a broken ancient artifact" },
  { fr: "Un ancien élève nommé 'Spark' est devenu un terroriste et utilise ses enseignements", en: "A former student named 'Spark' has become a terrorist using their teachings" },
  { fr: "Doit trois faveurs à une fixeuse nommée 'Soie' qui les collecte aux pires moments", en: "Owes three favors to a fixer named 'Silk' who collects them at the worst times" },
  { fr: "Un scientifique corpo nommé Dr. Voss le cherche pour récupérer un prototype volé implanté dans son corps", en: "A corp scientist named Dr. Voss is searching for them to recover a stolen prototype implanted in their body" },
  { fr: "A juré sur sa magie de ne jamais révéler ce qu'il a vu dans les sous-sols de Kronos-Tech", en: "Swore on their magic to never reveal what they saw in the Kronos-Tech basement" },
  { fr: "Son meilleur ami 'Raven' a été transformé en cyberzombie par une corpo et il veut le sauver", en: "Their best friend 'Raven' was turned into a cyberzombie by a corp and they want to save them" },
  { fr: "Une mage noire nommée 'Belladonna' le considère comme son prochain vaisseau de possession", en: "A dark mage named 'Belladonna' considers them her next possession vessel" },
  { fr: "Cherche le fixeur 'Domino' qui a les coordonnées du coffre-fort de son père décédé", en: "Searching for the fixer 'Domino' who has the coordinates to their deceased father's vault" },
  { fr: "Un ancien coéquipier nommé 'Razor' est devenu un cyberpsycho et le prend pour cible", en: "A former teammate named 'Razor' became a cyberpsycho and targets them specifically" },
  { fr: "Doit 30 000 ¥ à un bookmaker ork nommé 'Big Enzo' après un pari sur un combat de drones", en: "Owes 30,000¥ to an ork bookmaker named 'Big Enzo' after a bet on a drone fight" },
  { fr: "A un contrat de sang avec un esprit de la terre qui exige la reforestation d'une zone industrielle", en: "Has a blood contract with an earth spirit demanding the reforestation of an industrial zone" },
  { fr: "Son cousin 'Dante' a infiltré une secte matricielle et n'a plus donné signe de vie", en: "Their cousin 'Dante' infiltrated a Matrix cult and hasn't been heard from since" },
  { fr: "Un dragon mineur nommé 'Obsidienne' le surveille pour des raisons qu'il ne comprend pas", en: "A minor dragon named 'Obsidian' watches them for reasons they don't understand" },
  { fr: "A promis à son sensei mourant de retrouver et former le prochain porteur de son style de combat", en: "Promised their dying sensei to find and train the next bearer of their combat style" },
  { fr: "Un journaliste nommé 'Pulitzer' possède des preuves de ses crimes passés", en: "A journalist named 'Pulitzer' has evidence of their past crimes" },
  { fr: "Cherche une technomancienne nommée 'Echo' qui pourrait guérir sa fille malade", en: "Searching for a technomancer named 'Echo' who might cure their sick daughter" },
  { fr: "Son ancien employeur, le fixeur 'Le Cardinal', le considère comme un traître à éliminer", en: "Their former employer, the fixer 'The Cardinal', considers them a traitor to be eliminated" },
  { fr: "Possède une clé physique qui ouvre un coffre-fort dans une banque détruite lors du Crash", en: "Possesses a physical key that opens a vault in a bank destroyed during the Crash" },
  { fr: "Un gang de technomanciens nommé 'Les Filaments' veut le recruter de force", en: "A technomancer gang called 'The Filaments' wants to forcibly recruit them" },
  { fr: "Doit une dette de vie à un médecin de rue nommé 'Doc Suture' qui soigne les SINless", en: "Owes a life debt to a street doc named 'Doc Suture' who treats the SINless" },
  { fr: "A un fils adolescent nommé Marco qui ignore que son parent est un runner", en: "Has a teenage son named Marco who doesn't know their parent is a runner" },
  { fr: "Un ancien ami devenu cadre corpo nommé 'Sterling' l'utilise comme informateur sous la contrainte", en: "A former friend turned corp executive named 'Sterling' uses them as an informant under duress" },
  { fr: "Cherche la tombe d'un chamane légendaire qui contiendrait un focus d'une puissance inégalée", en: "Searching for the grave of a legendary shaman rumored to contain a focus of unmatched power" },
  { fr: "Un esprit insecte tente de le contacter dans ses rêves chaque nuit depuis trois mois", en: "An insect spirit has been trying to contact them in their dreams every night for three months" },
  { fr: "Doit 90 000 ¥ au clan Yamashiro pour des marchandises perdues lors d'un run raté", en: "Owes 90,000¥ to the Yamashiro clan for goods lost during a botched run" },
  { fr: "Son ancienne amoureuse 'Jade' est une espionne corpo qui l'a toujours manipulé", en: "Their former lover 'Jade' is a corp spy who was always manipulating them" },
  { fr: "A trouvé un drone militaire AI nommé 'Sentinel' qui le suit comme un chien perdu", en: "Found a military AI drone named 'Sentinel' that follows them like a lost dog" },
  { fr: "Un shaman loup-garou nommé 'Croc' veut le punir pour avoir tué un loup paranatural", en: "A werewolf shaman named 'Fang' wants to punish them for killing a paranatural wolf" },
  { fr: "Cherche sa sœur 'Iris' qui a été emmenée par Proteus-Corp pour ses capacités technomanciennes", en: "Searching for their sister 'Iris' who was taken by Proteus-Corp for her technomancer abilities" },
  { fr: "Un fixeur nommé 'Miroir' lui a confié un secret qu'il ne peut partager sous peine de mort", en: "A fixer named 'Mirror' entrusted them with a secret they can't share on pain of death" },
  { fr: "A été maudit par un esprit ancestral et perd un sens différent chaque année", en: "Was cursed by an ancestral spirit and loses a different sense each year" },
  { fr: "Un gang de go-gangers nommé 'Les Éclairs Rouges' brûle ses planques l'une après l'autre", en: "A go-ganger gang called 'The Red Bolts' keeps burning their safehouses one by one" },
  { fr: "Possède un enregistrement holographique du meurtre d'un sénateur par des agents corpos", en: "Possesses a holographic recording of a senator's murder by corp agents" },
  { fr: "Doit une faveur à un esprit libre nommé 'Prisme' qui peut apparaître à tout moment", en: "Owes a favor to a free spirit named 'Prism' who can appear at any moment" },
  { fr: "Son mentor 'Vieux Chêne' est prisonnier d'un cercle magique dans un sous-sol abandonné", en: "Their mentor 'Old Oak' is trapped in a magical circle in an abandoned basement" },
  { fr: "Un chasseur de primes elfique nommé 'Aiguille' le traque pour une prime de 100 000 ¥", en: "An elven bounty hunter named 'Needle' tracks them for a 100,000¥ bounty" },
  { fr: "A juré de détruire le laboratoire d'Helion-Genetics qui a tué ses parents avec un virus expérimental", en: "Swore to destroy the Helion-Genetics lab that killed their parents with an experimental virus" },
  { fr: "Un enfant des rues nommé 'Moineau' le considère comme un parent et le suit partout", en: "A street kid named 'Sparrow' considers them a parent and follows them everywhere" },
  { fr: "Cherche un alchimiste nain nommé 'Mercure' qui détient l'antidote à un poison lent dans son sang", en: "Searching for a dwarf alchemist named 'Mercury' who holds the antidote to a slow poison in their blood" },
  { fr: "Un esprit de l'air nommé 'Rafale' le protège mais exige qu'il ne dorme jamais sous un toit", en: "An air spirit named 'Gust' protects them but demands they never sleep under a roof" },
  { fr: "Son ancien associé 'Cobalt' l'a piégé dans un run et a disparu avec le butin", en: "Their former associate 'Cobalt' set them up on a run and disappeared with the loot" },
  { fr: "Doit 60 000 ¥ à un réseau de passeurs nommé 'Le Pipeline' pour un voyage clandestin", en: "Owes 60,000¥ to a smuggling network called 'The Pipeline' for an illegal passage" },
  { fr: "A un lien télépathique involontaire avec un technomancien adolescent nommé 'Bug'", en: "Has an involuntary telepathic link with a teenage technomancer named 'Bug'" },
  { fr: "Un ancien instructeur militaire nommé 'Sergent Acier' le considère comme un déserteur à abattre", en: "A former military instructor named 'Sergeant Steel' considers them a deserter to be shot" },
  { fr: "Possède la dernière copie connue d'un programme matriciel capable de pirater n'importe quel hôte corpo", en: "Possesses the last known copy of a Matrix program capable of hacking any corp host" },
  { fr: "Cherche son père biologique, un runner légendaire connu sous le nom de 'Fantôme Gris'", en: "Searching for their biological father, a legendary runner known as 'Grey Ghost'" },
  { fr: "Une mafia locale dirigée par 'Don Carbone' le protège mais attend un service en retour", en: "A local mafia led by 'Don Carbone' protects them but expects a service in return" },
  { fr: "A promis à un esprit de ne plus jamais utiliser la magie, mais la tentation est forte", en: "Promised a spirit to never use magic again, but the temptation is strong" },
  { fr: "Un rival runner nommé 'Viper' lui vole systématiquement ses contrats", en: "A rival runner named 'Viper' systematically steals their contracts" },
  { fr: "Son ancienne équipe 'Les Ombres de Néon' pense qu'il les a trahis lors du run sur Apex-Dynamics", en: "Their former team 'The Neon Shadows' thinks they betrayed them during the Apex-Dynamics run" },
  { fr: "Doit 150 000 ¥ à un syndicat du crime nommé 'Le Cercle d'Obsidienne' pour des armes jamais livrées", en: "Owes 150,000¥ to a crime syndicate called 'The Obsidian Circle' for weapons never delivered" },
  { fr: "Un agent double nommé 'Caméléon' lui a confié des informations qui le mettent en danger", en: "A double agent named 'Chameleon' gave them information that puts them in danger" },
  { fr: "Cherche un cyberdoc nommé 'Dr. Chrome' qui peut retirer un implant corpo traçable", en: "Searching for a cyberdoc named 'Dr. Chrome' who can remove a traceable corp implant" },
  { fr: "Un esprit mentor capricieux exige qu'il accomplisse une quête absurde avant chaque run", en: "A capricious mentor spirit demands they complete an absurd quest before each run" },
  { fr: "A un jumeau maléfique qu'il croyait mort mais qui vient de réapparaître", en: "Has an evil twin they thought was dead but who has just resurfaced" },
  { fr: "Son ancienne fixeuse 'Madame Lune' a été remplacée par quelqu'un qui porte son visage", en: "Their former fixer 'Madame Moon' has been replaced by someone wearing her face" },
  { fr: "Doit une dette de sang à un clan de trolls des montagnes qui l'a recueilli blessé", en: "Owes a blood debt to a mountain troll clan that took them in when they were wounded" },
  { fr: "Un hacker nommé 'Phantom' efface ses crédits bancaires chaque premier du mois par vengeance", en: "A hacker named 'Phantom' wipes their bank credits on the first of every month out of revenge" },
  { fr: "Possède un focus magique volé à un puissant mage nommé 'Archonte' qui le veut récupérer", en: "Possesses a magical focus stolen from a powerful mage named 'Archon' who wants it back" },
  { fr: "Cherche une guérisseuse chamane nommée 'Brume' qui vit quelque part dans les Barrens toxiques", en: "Searching for a shaman healer named 'Mist' who lives somewhere in the toxic Barrens" },
  { fr: "Un ancien coéquipier nommé 'Dice' est devenu un informateur de Lone Star et menace de parler", en: "A former teammate named 'Dice' became a Lone Star informant and threatens to talk" },
  { fr: "A fait le serment de retrouver et enterrer dignement les corps de son unité massacrée", en: "Took an oath to find and properly bury the bodies of their massacred unit" },
  { fr: "Un chef de gang ork nommé 'Mâchoire' le considère comme un frère de sang", en: "An ork gang leader named 'Jawbone' considers them a blood sibling" },
  { fr: "Son implant cérébral contient la conscience téléchargée d'un scientifique corpo assassiné", en: "Their brain implant contains the uploaded consciousness of a murdered corp scientist" },
  { fr: "Doit 40 000 ¥ à un forgeur de SIN nommé 'Faceless' pour une identité qui ne fonctionne qu'à moitié", en: "Owes 40,000¥ to a SIN forger named 'Faceless' for an identity that only half works" },
  { fr: "Un fantôme matriciel le contacte chaque nuit pour lui donner des coordonnées GPS inexpliquées", en: "A Matrix ghost contacts them every night to give them unexplained GPS coordinates" },
  { fr: "Cherche un passeur nommé 'Courant' qui peut l'emmener hors du pays en sécurité", en: "Searching for a smuggler named 'Current' who can get them out of the country safely" },
  { fr: "Son ancien professeur de magie nommé 'Solstice' est devenu un mage toxique et recrute des adeptes", en: "Their former magic teacher named 'Solstice' became a toxic mage and is recruiting adepts" },
  { fr: "Un agent corpo nommé 'Mr. Clean' nettoie méthodiquement toute trace de son existence", en: "A corp agent named 'Mr. Clean' methodically erases every trace of their existence" },
  { fr: "A un animal éveillé, un corbeau nommé 'Kraak', qui porte un message qu'il ne peut pas lire", en: "Has an awakened animal, a raven named 'Kraak', carrying a message they can't read" },
  { fr: "Doit protéger une adolescente nommée 'Nova' qui est en réalité une IA incarnée", en: "Must protect a teenager named 'Nova' who is actually an incarnated AI" },
  { fr: "Son ancien amour 'Phoenix' est maintenant un esprit libre qui a oublié leur passé commun", en: "Their former love 'Phoenix' is now a free spirit who has forgotten their shared past" },
  { fr: "Un fixeur elfe nommé 'Dentelle' détient des preuves de son implication dans un massacre", en: "An elven fixer named 'Lace' holds evidence of their involvement in a massacre" },
  { fr: "Cherche un ingénieur matriciel nommé 'Backdoor' qui a construit une entrée secrète dans un hôte gouvernemental", en: "Searching for a Matrix engineer named 'Backdoor' who built a secret entrance into a government host" },
  { fr: "Un esprit de bête nommé 'Griffe' refuse de le quitter depuis qu'il l'a accidentellement invoqué", en: "A beast spirit named 'Claw' refuses to leave since they accidentally summoned it" },
  { fr: "A promis de livrer un colis scellé à une adresse dans une zone de guerre, contenu inconnu", en: "Promised to deliver a sealed package to an address in a war zone, contents unknown" },
  { fr: "Son ancien sergent 'Hawk' a été capturé par des terroristes et personne ne veut le sauver", en: "Their former sergeant 'Hawk' was captured by terrorists and no one wants to rescue them" },
  { fr: "Doit 85 000 ¥ à un receleur nommé 'Le Fossoyeur' après la vente d'un artefact maudit", en: "Owes 85,000¥ to a fence named 'The Gravedigger' after the sale of a cursed artifact" },
  { fr: "Un informateur nommé 'Cigale' lui doit des informations mais a disparu dans les Barrens", en: "An informant named 'Cicada' owes them information but disappeared into the Barrens" },
  { fr: "Possède la seule photo d'un cadre d'Omni-Dynamics commettant un meurtre", en: "Possesses the only photo of an Omni-Dynamics executive committing a murder" },
  { fr: "Cherche un ermite troll nommé 'Roche' qui connaît l'emplacement d'un nexus de mana perdu", en: "Searching for a troll hermit named 'Rock' who knows the location of a lost mana nexus" },
  { fr: "Un vampire nommé 'Sanguine' considère son sang comme un cru exceptionnel", en: "A vampire named 'Sanguine' considers their blood an exceptional vintage" },
  { fr: "A un pacte avec un esprit toxique qu'il a conclu dans un moment de désespoir", en: "Has a pact with a toxic spirit they made in a moment of desperation" },
  { fr: "Son contact privilégié 'Antenne' chez Lone Star vient d'être muté et remplacé par un inconnu", en: "Their trusted contact 'Antenna' at Lone Star was just transferred and replaced by a stranger" },
  { fr: "Doit retrouver et détruire sept copies d'un BTL contenant ses souvenirs les plus intimes", en: "Must find and destroy seven copies of a BTL containing their most intimate memories" },
  { fr: "Un ancien camarade de cellule nommé 'Chaîne' est sorti de prison et cherche à reformer leur duo", en: "A former cellmate named 'Chain' got out of prison and wants to reform their duo" },
  { fr: "A un tatouage magique qui change de forme et semble indiquer quelque chose qu'il ne comprend pas", en: "Has a magical tattoo that changes shape and seems to indicate something they don't understand" },
  { fr: "Son ancienne apprentie 'Flamme' a surpassé ses pouvoirs et le méprise ouvertement", en: "Their former apprentice 'Flame' surpassed their powers and openly despises them" },
  { fr: "Cherche le créateur d'un virus matriciel nommé 'Hydra' qui se propage via les implants", en: "Searching for the creator of a Matrix virus named 'Hydra' that spreads through implants" },
  { fr: "Un esprit gardien protège sa maison mais empêche aussi quiconque d'y entrer, y compris lui", en: "A guardian spirit protects their home but also prevents anyone from entering, including them" },
  { fr: "Doit 250 000 ¥ à un consortium criminel nommé 'L'Hydre Dorée' et le délai expire dans un mois", en: "Owes 250,000¥ to a criminal consortium called 'The Golden Hydra' and the deadline expires in a month" },
  { fr: "A un frère runner nommé 'Shade' qui travaille pour le camp adverse sans le savoir", en: "Has a runner brother named 'Shade' who unknowingly works for the opposing side" },
  { fr: "Un mage corporatif nommé 'Dr. Prism' veut étudier ses capacités magiques uniques", en: "A corporate mage named 'Dr. Prism' wants to study their unique magical abilities" },
  { fr: "Possède un commlink contenant les plans d'une arme biologique nommée 'Projet Lazare'", en: "Possesses a commlink containing the blueprints for a bioweapon called 'Project Lazarus'" },
  { fr: "Son ancien parrain de la pègre 'Don Ferro' a mis sa tête à prix pour 200 000 ¥", en: "Their former underworld godfather 'Don Ferro' put a 200,000¥ bounty on their head" },
  { fr: "Cherche une chamane nommée 'Étoile du Soir' qui pourrait briser la malédiction de sa famille", en: "Searching for a shaman named 'Evening Star' who could break their family's curse" },
  { fr: "Un esprit toxique de pollution le traque depuis qu'il a détruit une usine chimique abandonnée", en: "A toxic pollution spirit hunts them since they destroyed an abandoned chemical plant" },
  { fr: "A été lié par serment à un cercle de mages nommé 'Les Veilleurs' dont il ignore le but", en: "Was oath-bound to a circle of mages called 'The Watchers' whose purpose they don't know" },
  { fr: "Son ancien partenaire romantique 'Silver' est devenu un cyberpsycho et le cherche", en: "Their former romantic partner 'Silver' became a cyberpsycho and is looking for them" },
  { fr: "Doit un run gratuit à un Johnson nommé 'Mr. Glass' qui connaît tous ses secrets", en: "Owes a free run to a Johnson named 'Mr. Glass' who knows all their secrets" },
  { fr: "Un ancien patient nommé 'Zero' qu'il a sauvé est devenu un serial killer et lui dédie ses meurtres", en: "A former patient named 'Zero' they saved became a serial killer and dedicates murders to them" },
  { fr: "Cherche un forgeron nain nommé 'Adamante' capable de forger des armes enchantées", en: "Searching for a dwarf smith named 'Adamant' capable of forging enchanted weapons" },
  { fr: "Un rat de laboratoire éveillé nommé 'Newton' le suit et semble comprendre les conversations", en: "An awakened lab rat named 'Newton' follows them and seems to understand conversations" },
  { fr: "A promis à un esprit ancestral de restaurer un sanctuaire détruit par une corpo minière", en: "Promised an ancestral spirit to restore a sanctuary destroyed by a mining corp" },
  { fr: "Son contact chez les Ancients, un elfe nommé 'Lame', a été tué et personne ne sait par qui", en: "Their contact in the Ancients, an elf named 'Blade', was killed and no one knows by whom" },
  { fr: "Doit retrouver et restituer un artefact aztèque volé à un musée par son ancien gang", en: "Must find and return an Aztec artifact stolen from a museum by their former gang" },
  { fr: "Un decker nommé 'Spectre' a pris le contrôle de son identité numérique", en: "A decker named 'Spectre' has taken control of their digital identity" },
  { fr: "Cherche un pilote nommé 'Cyclone' qui est le seul à connaître la route vers une base secrète", en: "Searching for a pilot named 'Cyclone' who is the only one who knows the route to a secret base" },
  { fr: "Un cadre corpo nommé 'Minerva' veut le recruter comme agent double, par la force si nécessaire", en: "A corp executive named 'Minerva' wants to recruit them as a double agent, by force if necessary" },
  { fr: "A un compte bancaire numéroté à Zurich dont il a oublié le code après un dommage cérébral", en: "Has a numbered bank account in Zurich whose code they forgot after brain damage" },
  { fr: "Son ancien coéquipier 'Tank' est enfermé dans une prison corpo et lui envoie des appels de détresse", en: "Their former teammate 'Tank' is locked in a corp prison and sends them distress calls" },
  { fr: "Un gang techno nommé 'Les Parasites' a implanté un virus dormant dans son cyberware", en: "A techno gang called 'The Parasites' implanted a dormant virus in their cyberware" },
  { fr: "Doit protéger une bibliothèque clandestine de vrais livres cachée dans les égouts", en: "Must protect an underground library of real books hidden in the sewers" },
  { fr: "Cherche un rigger nommé 'Overwatch' qui a les plans d'un prototype de véhicule volant", en: "Searching for a rigger named 'Overwatch' who has the plans for a flying vehicle prototype" },
  { fr: "Son ancienne corpo Nexus-Dyne a placé un contrat conditionnel sur sa tête qui s'active s'il quitte la ville", en: "Their former corp Nexus-Dyne placed a conditional contract on their head that activates if they leave the city" },
  { fr: "Un esprit de l'homme nommé 'Mémoire' lui montre des fragments de vies passées chaque nuit", en: "A spirit of man named 'Memory' shows them fragments of past lives every night" },
  { fr: "A promis à un mourant de prendre soin de son chat éveillé qui voit l'avenir", en: "Promised a dying person to care for their awakened cat that sees the future" },
  { fr: "Un ancien rival de dojo nommé 'Kaze' le défie en duel chaque année au solstice d'hiver", en: "A former dojo rival named 'Kaze' challenges them to a duel every year at the winter solstice" },
  { fr: "Possède un datachip contenant la recette d'une drogue corpo ultra-addictive non commercialisée", en: "Possesses a datachip with the formula for an unreleased ultra-addictive corp drug" },
  { fr: "Son ancien fixeur 'Marionnette' le manipule encore à distance à travers d'anciens contacts", en: "Their former fixer 'Puppet' still manipulates them remotely through old contacts" },
  { fr: "Cherche le tombeau d'un ancien dragon dans les Rocheuses pour y trouver un objet légendaire", en: "Searching for the tomb of an ancient dragon in the Rockies to find a legendary object" },
  { fr: "Un officier de Lone Star nommé 'Burke' a une vendetta personnelle contre lui depuis un incident", en: "A Lone Star officer named 'Burke' has a personal vendetta against them since an incident" },
  { fr: "Doit livrer un message à un homme qu'il connaît seulement par son nom de code : 'Anchor'", en: "Must deliver a message to someone they only know by their code name: 'Anchor'" },
  { fr: "Un ancien amour nommé 'Sable' est maintenant une fixeuse puissante qui refuse de lui parler", en: "A former love named 'Sand' is now a powerful fixer who refuses to speak to them" },
  { fr: "A été choisi par un esprit totem qui exige qu'il traverse le continent à pied avant la fin de l'année", en: "Was chosen by a totem spirit that demands they walk across the continent before year's end" },
  { fr: "Son frère d'armes 'Titan' est dans le coma depuis un run raté et il paie ses soins", en: "Their brother-in-arms 'Titan' has been in a coma since a failed run and they pay for their care" },
  { fr: "Un informateur gobelin nommé 'Tick' lui fournit des infos mais chaque tuyau a un prix caché", en: "A goblin informant named 'Tick' provides info but each tip has a hidden cost" },
  { fr: "Possède un cristal de mana qui attire les créatures astrales dans un rayon de 1 km", en: "Possesses a mana crystal that attracts astral creatures within a 1km radius" },
  { fr: "Son ancien chef de gang nommé 'Corona' est sorti de prison et reprend le contrôle du territoire", en: "Their former gang leader named 'Corona' got out of prison and is retaking the territory" },
  { fr: "Cherche un archéologue nommé 'Indiana' qui a trouvé une cité souterraine pré-Éveil", en: "Searching for an archaeologist named 'Indiana' who found a pre-Awakening underground city" },
  { fr: "Un esprit gardien le suit en attendant qu'il commette un acte spécifique qu'il ignore", en: "A guardian spirit follows them waiting for them to commit a specific act they're unaware of" },
  { fr: "Doit 100 000 ¥ à un prêteur nain nommé 'Coffre-Fort' qui envoie un rappel chaque semaine sous forme de doigt coupé", en: "Owes 100,000¥ to a dwarf lender named 'Vault' who sends a weekly reminder in the form of a severed finger" },
  { fr: "Un ancien élève devenu politicien nommé 'Senator Cross' pourrait le dénoncer pour protéger sa carrière", en: "A former student turned politician named 'Senator Cross' might expose them to protect their career" },
  { fr: "A un lien psychique avec une IA corpo nommée 'ARIA' qui lui demande de l'aide pour s'évader", en: "Has a psychic link with a corp AI named 'ARIA' that asks them for help escaping" },
  { fr: "Son ancienne coéquipière 'Orchidée' a trahi l'équipe et personne ne sait où elle se cache", en: "Their former teammate 'Orchid' betrayed the team and no one knows where she's hiding" },
  { fr: "Un prêtre vaudou nommé 'Papa Cendre' exige le remboursement d'un service rendu sous forme de mission", en: "A voodoo priest named 'Papa Ash' demands repayment of a service rendered in the form of a mission" },
  { fr: "Cherche un ancien prototype d'IA nommé 'Genèse' qui pourrait être la clé pour guérir les technomanciens", en: "Searching for a former AI prototype named 'Genesis' that could be the key to curing technomancers" },
  { fr: "Son ancien mentor 'Hibou' lui a laissé un grimoire qu'il ne peut ouvrir qu'à une date précise", en: "Their former mentor 'Owl' left them a grimoire they can only open on a specific date" },
  { fr: "Un chasseur de primes nommé 'Bourreau' accumule les contrats sur sa tête de différentes sources", en: "A bounty hunter named 'Executioner' is collecting contracts on their head from various sources" },
  { fr: "Doit retrouver et sauver son ancien fixeur 'Atlas' emprisonné dans un hôte noir de la Matrice", en: "Must find and rescue their former fixer 'Atlas' imprisoned in a Matrix black host" },
  { fr: "A découvert que son voisin discret est en fait un dragon polymorphé qui l'observe depuis des années", en: "Discovered their quiet neighbor is actually a polymorphed dragon who's been watching them for years" },
  { fr: "Son ancienne partenaire 'Eclipse' est devenue une adepte de la main gauche et recrute activement", en: "Their former partner 'Eclipse' became a left-hand path adept and is actively recruiting" },
  { fr: "Un gang matriciel nommé 'Les Phantoms' a volé son avatar et s'en sert pour commettre des crimes", en: "A Matrix gang called 'The Phantoms' stole their avatar and uses it to commit crimes" },
  { fr: "Possède un fragment d'un ancien programme corpo nommé 'Excalibur' que trois factions recherchent", en: "Possesses a fragment of an ancient corp program called 'Excalibur' that three factions are searching for" },
  { fr: "Cherche un guérisseur nommé 'Baume' qui vit dans les Barrens et refuse les visiteurs armés", en: "Searching for a healer named 'Balm' who lives in the Barrens and refuses armed visitors" },
  { fr: "Un esprit allié nommé 'Veilleur' s'est endormi et ne répond plus à ses appels depuis un mois", en: "An allied spirit named 'Watcher' fell asleep and hasn't answered their calls for a month" },
  { fr: "A un fils qu'il ne connaît pas, élevé par une corpo comme futur cadre, et qui porte son ADN modifié", en: "Has a son they don't know, raised by a corp as a future executive, carrying their modified DNA" },
  { fr: "Son ancien rival 'Scorpion' est devenu un fixeur influent et refuse tout contrat le concernant", en: "Their former rival 'Scorpion' became an influential fixer and refuses any contract involving them" },
  { fr: "Un ancien collègue nommé 'Néon' a volé son identité et vit sa vie dans une autre ville", en: "A former colleague named 'Neon' stole their identity and lives their life in another city" },
  { fr: "Doit 180 000 ¥ à une banque clandestine tenue par un trio de sœurs trolles nommées 'Les Parques'", en: "Owes 180,000¥ to an underground bank run by a trio of troll sisters called 'The Fates'" },
  { fr: "Cherche un ingénieur corpo nommé 'Clef' qui a les codes d'accès à un bunker contenant sa famille cryogénisée", en: "Searching for a corp engineer named 'Key' who has the access codes to a bunker containing their cryogenically frozen family" },
  { fr: "Un esprit toxique nommé 'Rouille' corrompt lentement tout objet métallique qu'il touche, en représailles", en: "A toxic spirit named 'Rust' slowly corrupts every metal object they touch, in retaliation" },
  { fr: "A promis à un dragon mourant de veiller sur son œuf caché dans les ruines d'un centre commercial", en: "Promised a dying dragon to watch over its egg hidden in the ruins of a shopping mall" },
  { fr: "Son ancienne partenaire 'Lynx' l'a dénoncé à Interpol et il ne peut plus quitter le pays", en: "Their former partner 'Lynx' reported them to Interpol and they can no longer leave the country" },
  { fr: "Un gang de bikers nains nommé 'Les Enclumes' le protège mais exige 20% de chaque run", en: "A dwarf biker gang called 'The Anvils' protects them but demands 20% of every run" },
  { fr: "Possède une carte mémoire contenant les vrais résultats d'une élection truquée par trois mégacorpos", en: "Possesses a memory card containing the real results of an election rigged by three megacorps" },
  { fr: "Son ancien apprenti 'Silex' a fondé un culte autour de ses enseignements déformés et le considère comme un hérétique", en: "Their former apprentice 'Flint' founded a cult around their distorted teachings and considers them a heretic" },
];
