/** Bilingual flavor entry */
export interface FlavorEntry {
  fr: string;
  en: string;
}

// ═══════════════════════════════════════════════════════════════
// PHYSICAL TRAITS — Distinctive visual features
// ═══════════════════════════════════════════════════════════════

export const PHYSICAL_TRAITS: FlavorEntry[] = [
  { fr: "Cicatrice de balle en travers de la joue gauche", en: "Bullet scar across the left cheek" },
  { fr: "Bras chrome qui grince quand il pleut", en: "Chrome arm that creaks when it rains" },
  { fr: "Mohawk néon qui change de couleur selon l'humeur", en: "Neon mohawk that changes color with mood" },
  { fr: "Cyberyeux rouges luminescents", en: "Glowing red cybereyes" },
  { fr: "Datajack visible sur la tempe droite entouré de tissu cicatriciel", en: "Visible datajack on the right temple surrounded by scar tissue" },
  { fr: "Plaques dermiques sur les phalanges, usées par les coups", en: "Dermal plating on the knuckles, worn from punching" },
  { fr: "Tatouage de gang à moitié brûlé à l'acide sur le cou", en: "Gang tattoo half-burned with acid on the neck" },
  { fr: "Défenses d'orc coiffées d'or avec des runes gravées", en: "Ork tusks capped in gold with engraved runes" },
  { fr: "Oreilles d'elfe percées de douze anneaux chacune", en: "Elf ears pierced with twelve rings each" },
  { fr: "Barbe de nain tressée avec des fils de fibre optique", en: "Dwarf beard braided with fiber optic wires" },
  { fr: "Langue bifide qui frétille quand il réfléchit", en: "Split tongue that flickers when thinking" },
  { fr: "LEDs sous-dermiques le long de la mâchoire, bleu glacé", en: "Subdermal LEDs along the jawline, ice blue" },
  { fr: "Toutes les dents remplacées par du chrome poli", en: "All teeth replaced with polished chrome" },
  { fr: "Boiterie prononcée de la jambe gauche, ancienne blessure", en: "Pronounced limp on the left leg, old wound" },
  { fr: "Auriculaire manquant à la main droite", en: "Missing pinky finger on the right hand" },
  { fr: "Albinos, peau blanche comme la craie et yeux roses", en: "Albino, chalk-white skin and pink eyes" },
  { fr: "Hétérochromie : un oeil vert naturel, un cyberyeux doré", en: "Heterochromia: one natural green eye, one golden cybereye" },
  { fr: "Froncement permanent, comme gravé dans le visage", en: "Permanent scowl, as if carved into the face" },
  { fr: "Cornes de troll limées au ras du crâne, traces de sang séché", en: "Troll horns filed down to the skull, traces of dried blood" },
  { fr: "Trench-coat avec beaucoup trop de poches, toutes pleines", en: "Trench coat with far too many pockets, all full" },
  { fr: "Lunettes miroir soudées au visage, impossible de voir les yeux", en: "Mirrorshades welded to the face, impossible to see the eyes" },
  { fr: "Bottes de combat avec des éperons rétractables", en: "Combat boots with retractable spurs" },
  { fr: "Scarification rituelle en spirale sur tout l'avant-bras", en: "Ritual scarification spiraling across the entire forearm" },
  { fr: "Brûlure d'acide couvrant la moitié droite du visage", en: "Acid burn covering the right half of the face" },
  { fr: "Main cybernétique avec des doigts trop longs, presque arachnéens", en: "Cybernetic hand with fingers too long, almost arachnid-like" },
  { fr: "Crâne rasé avec un code-barres tatoué sur la nuque", en: "Shaved head with a barcode tattooed on the back of the neck" },
  { fr: "Oeil cybernétique qui clignote en rouge quand il scanne", en: "Cybereye that blinks red when scanning" },
  { fr: "Vieille cicatrice de couteau du menton à l'oreille", en: "Old knife scar from chin to ear" },
  { fr: "Cheveux blancs prématurés, visage encore jeune", en: "Prematurely white hair, face still young" },
  { fr: "Bras cybernétique couvert de stickers de gangs", en: "Cybernetic arm covered in gang stickers" },
  { fr: "Nez cassé plusieurs fois, tordu vers la gauche", en: "Nose broken multiple times, twisted to the left" },
  { fr: "Tatouage facial de circuit imprimé, encre phosphorescente", en: "Circuit board facial tattoo, phosphorescent ink" },
  { fr: "Jambe cybernétique visible sous un pantalon déchiré", en: "Cybernetic leg visible under torn pants" },
  { fr: "Iris modifiés en forme de croix, lueur violette", en: "Modified irises in a cross shape, purple glow" },
  { fr: "Griffes rétractables sous les ongles, toujours un peu sorties", en: "Retractable claws under the nails, always slightly extended" },
  { fr: "Peau tannée comme du vieux cuir, marquée par le soleil toxique", en: "Skin tanned like old leather, marked by toxic sun" },
  { fr: "Mèche de cheveux synthétiques argentés dans une crinière noire", en: "Streak of silver synthetic hair in a black mane" },
  { fr: "Oreilles pointues ajoutées chirurgicalement, mal cicatrisées", en: "Surgically added pointed ears, poorly healed" },
  { fr: "Implant crânien visible comme une plaque de métal sur le front", en: "Visible cranial implant like a metal plate on the forehead" },
  { fr: "Mains couvertes de callosités et de micro-brûlures d'électronique", en: "Hands covered in calluses and micro-burns from electronics" },
  { fr: "Veste en cuir blindé usée jusqu'à la trame", en: "Armored leather jacket worn down to the weave" },
  { fr: "Cache-oeil avec un capteur infrarouge intégré", en: "Eyepatch with a built-in infrared sensor" },
  { fr: "Mâchoire inférieure en chrome, articulée avec un léger déclic", en: "Chrome lower jaw, articulated with a slight click" },
  { fr: "Veines noires visibles sous une peau translucide, effet de drogue", en: "Black veins visible under translucent skin, drug side effect" },
  { fr: "Doigts cybernétiques qui tambourinent tout seuls", en: "Cybernetic fingers that drum on their own" },
  { fr: "Crête iroquoise faite de fibres optiques clignotantes", en: "Mohawk made of blinking fiber optic strands" },
  { fr: "Marque au fer rouge d'un syndicat criminel sur l'épaule", en: "Criminal syndicate brand mark on the shoulder" },
  { fr: "Un oeil complètement blanc, aveugle de ce côté", en: "One eye completely white, blind on that side" },
  { fr: "Cicatrices d'éclats de grenade sur tout le torse", en: "Grenade shrapnel scars all over the torso" },
  { fr: "Peau greffée de couleur différente sur le bras gauche", en: "Grafted skin of a different color on the left arm" },
  { fr: "Cybermain avec un briquet intégré dans le pouce", en: "Cyberhand with a lighter built into the thumb" },
  { fr: "Queue de cheval attachée avec du fil de fer barbelé", en: "Ponytail tied with barbed wire" },
  { fr: "Joues creuses, pommettes saillantes, regard de prédateur", en: "Hollow cheeks, sharp cheekbones, predator's gaze" },
  { fr: "Implant vocal, voix synthétique métallique", en: "Voice implant, metallic synthetic voice" },
  { fr: "Moignon de corne de troll transformé en support de commlink", en: "Troll horn stump converted into a commlink mount" },
  { fr: "Trois entailles parallèles sur chaque joue, scarification tribale", en: "Three parallel cuts on each cheek, tribal scarification" },
  { fr: "Bras cybernétique peint en camouflage urbain, écaillé", en: "Cybernetic arm painted in urban camo, chipped" },
  { fr: "Collier de balles usagées autour du cou", en: "Necklace of spent bullet casings around the neck" },
  { fr: "Oeil cybernétique avec zoom visible, pupille qui s'ouvre en iris mécanique", en: "Cybereye with visible zoom, pupil opening as a mechanical iris" },
  { fr: "Vieille brûlure de laser sur toute la longueur de l'avant-bras", en: "Old laser burn running the full length of the forearm" },
  { fr: "Crâne tatoué de symboles mystiques qui semblent luire dans le noir", en: "Skull tattooed with mystical symbols that seem to glow in the dark" },
  { fr: "Défenses d'orc peintes en noir avec des pointes en acier", en: "Ork tusks painted black with steel tips" },
  { fr: "Monocle cybernétique vissé dans l'orbite gauche", en: "Cybernetic monocle screwed into the left eye socket" },
  { fr: "Cicatrice en forme d'étoile sur le dos de la main, impact de balle", en: "Star-shaped scar on the back of the hand, bullet impact" },
  { fr: "Peau pâle presque bleutée, jamais exposée au soleil", en: "Pale almost bluish skin, never exposed to sunlight" },
  { fr: "Bottes magnétiques qui claquent sur le métal", en: "Magnetic boots that clank on metal" },
  { fr: "Dreadlocks synthétiques avec des fils de données tressés dedans", en: "Synthetic dreadlocks with data cables braided in" },
  { fr: "Grande taille maigre, silhouette de poteau électrique", en: "Tall and thin, electric pole silhouette" },
  { fr: "Main gauche avec seulement trois doigts, les autres perdus au combat", en: "Left hand with only three fingers, the others lost in combat" },
  { fr: "Tatouage de serpent qui s'enroule autour du cou et disparaît sous le col", en: "Snake tattoo coiling around the neck and disappearing under the collar" },
  { fr: "Sourcils rasés et remplacés par des lignes de chrome", en: "Eyebrows shaved and replaced with chrome lines" },
  { fr: "Vieille armure corporelle portée par-dessus un costume trois-pièces", en: "Old body armor worn over a three-piece suit" },
  { fr: "Lèvres fendues par une cicatrice verticale", en: "Lips split by a vertical scar" },
  { fr: "Main cybernétique avec un affichage holographique intégré dans la paume", en: "Cybernetic hand with a holographic display built into the palm" },
  { fr: "Pieds cybernétiques digitigrades, marche sur la pointe", en: "Digitigrade cybernetic feet, walks on tiptoes" },
  { fr: "Peau couverte de micro-écailles, modification génétique ratée", en: "Skin covered in micro-scales, failed genetic modification" },
  { fr: "Bandana blindé qui ne quitte jamais la tête", en: "Armored bandana that never leaves the head" },
  { fr: "Fibres musculaires visibles sous une peau trop fine", en: "Muscle fibers visible under too-thin skin" },
  { fr: "Moustache en guidon de vélo, anachronisme assumé", en: "Handlebar mustache, unapologetic anachronism" },
  { fr: "Implants dermiques en forme d'écailles de dragon sur les bras", en: "Dermal implants shaped like dragon scales on the arms" },
  { fr: "Colonne vertébrale renforcée, bosse métallique visible dans le dos", en: "Reinforced spine, metallic bump visible on the back" },
  { fr: "Traces de brûlures chimiques sur les mains, accidents de labo", en: "Chemical burn marks on the hands, lab accidents" },
  { fr: "Un seul gros sourcil continu, regard menaçant naturel", en: "One single continuous eyebrow, naturally menacing look" },
  { fr: "Cheveux bleus électriques coupés en carré net", en: "Electric blue hair cut in a sharp bob" },
  { fr: "Pommettes implantées avec des diodes qui clignotent au rythme cardiaque", en: "Implanted cheekbones with diodes that blink with heartbeat" },
  { fr: "Bras couvert de cicatrices de morsures, dresseur de paracritters", en: "Arm covered in bite scars, paracritter handler" },
  { fr: "Dentier cybernétique qui brille dans le noir", en: "Cybernetic dentures that glow in the dark" },
  { fr: "Cache-nez permanent même en intérieur, visage jamais montré", en: "Permanent face mask even indoors, face never shown" },
  { fr: "Oeil cybernétique avec une croix au lieu d'une pupille", en: "Cybereye with a crosshair instead of a pupil" },
  { fr: "Peau tatouée intégralement en noir d'encre, visage compris", en: "Entire skin tattooed in solid black ink, face included" },
  { fr: "Implant de corne unique au milieu du front, style licorne", en: "Single horn implant in the middle of the forehead, unicorn style" },
  { fr: "Gorgeret blindé en acier autour du cou", en: "Armored steel gorget around the neck" },
  { fr: "Ongles en céramique renforcée, vernis en chrome", en: "Reinforced ceramic nails, chrome polish" },
  { fr: "Sourcil coupé par une vieille cicatrice, regard asymétrique", en: "Eyebrow cut by an old scar, asymmetric gaze" },
  { fr: "Bras cybernétique qui émet un léger bourdonnement constant", en: "Cybernetic arm that emits a faint constant hum" },
  { fr: "Tatouage UV invisible sauf sous lumière noire, couvre tout le visage", en: "UV tattoo invisible except under blacklight, covers the whole face" },
  { fr: "Oreille arrachée et remplacée par un capteur audio chrome", en: "Ear torn off and replaced with a chrome audio sensor" },
  { fr: "Veste à col haut qui cache une horrible cicatrice de strangulation", en: "High-collar jacket hiding a horrible strangulation scar" },
  { fr: "Doigts de la main gauche tous cybernétiques, chacun d'un métal différent", en: "Left hand fingers all cybernetic, each a different metal" },
  { fr: "Strabisme léger qui donne un air décalé", en: "Slight strabismus giving an off-kilter look" },
  { fr: "Crâne partiellement rasé avec des ports de connexion neurale alignés", en: "Partially shaved skull with neural connection ports lined up" },
  { fr: "Peau bronzée artificielle, orange fluo peu naturel", en: "Artificial tan, unnaturally fluorescent orange" },
  { fr: "Machoire carrée massive, probablement renforcée au titane", en: "Massive square jaw, probably titanium-reinforced" },
  { fr: "Main droite enveloppée en permanence dans un bandage sale", en: "Right hand permanently wrapped in a dirty bandage" },
  { fr: "Yeux enfoncés dans les orbites, cerné en permanence", en: "Deep-set eyes, permanently dark circles" },
  { fr: "Petites cornes de diablotin sur le front, implants cosmétiques", en: "Small devil horns on the forehead, cosmetic implants" },
  { fr: "Marques de griffes profondes en travers du dos, visible au col", en: "Deep claw marks across the back, visible at the collar" },
  { fr: "Cyberbras avec un tatouage de dragon peint par-dessus le chrome", en: "Cyberarm with a dragon tattoo painted over the chrome" },
  { fr: "Lentilles de contact à pupille féline verticale", en: "Contact lenses with vertical feline pupils" },
  { fr: "Vieux piercing au septum tordu par un coup de poing", en: "Old septum piercing bent from a punch" },
  { fr: "Mains énormes disproportionnées par rapport au corps frêle", en: "Disproportionately huge hands on a frail body" },
  { fr: "Gants en cuir qui ne quittent jamais les mains", en: "Leather gloves that never leave the hands" },
  { fr: "Micro-antenne rétractable derrière l'oreille", en: "Retractable micro-antenna behind the ear" },
  { fr: "Peau grêlée de marques de variole, survivant des Barrens", en: "Pockmarked skin, Barrens survivor" },
  { fr: "Demi-visage recouvert de plaques dermiques argentées", en: "Half face covered in silver dermal plates" },
  { fr: "Chaîne épaisse en acier portée comme un collier, ancienne entrave", en: "Thick steel chain worn as a necklace, former shackle" },
  { fr: "Cheveux en brosse courte avec un sillon de cicatrice visible", en: "Short crew cut with a visible scar furrow" },
  { fr: "Petit implant lumineux sous la peau de la gorge, pulse doucement", en: "Small luminous implant under the throat skin, pulsing gently" },
  { fr: "Jambe cybernétique qui fait un bruit de servomoteur à chaque pas", en: "Cybernetic leg that makes a servo noise with every step" },
  { fr: "Coupure nette d'oreille, tranchée au monofilament", en: "Clean ear cut, sliced by monofilament" },
  { fr: "Veines cybernétiques visibles sous la peau des tempes", en: "Cybernetic veins visible under the skin at the temples" },
  { fr: "Grand manteau de pluie qui traîne par terre, toujours humide", en: "Long rain coat dragging on the ground, always damp" },
  { fr: "Implant nasal chromé, narines rectangulaires", en: "Chrome nasal implant, rectangular nostrils" },
  { fr: "Muscles surdéveloppés d'un côté, atrophiés de l'autre", en: "Overdeveloped muscles on one side, atrophied on the other" },
  { fr: "Index droit remplacé par un petit laser de visée", en: "Right index finger replaced with a small targeting laser" },
  { fr: "Piercings en chaîne reliant l'oreille à la narine", en: "Chain piercings linking ear to nostril" },
  { fr: "Grande balafre en X sur le front, marque d'exécution ratée", en: "Large X scar on the forehead, mark of a failed execution" },
  { fr: "Barbe de trois jours perpétuelle, jamais plus, jamais moins", en: "Perpetual three-day stubble, never more, never less" },
  { fr: "Cou épais comme un tronc, renforcé d'implants musculaires", en: "Neck thick as a trunk, reinforced with muscle implants" },
  { fr: "Holster d'épaule visible en permanence, même sans arme dedans", en: "Shoulder holster permanently visible, even without a weapon in it" },
  { fr: "Peau qui luit faiblement dans le noir, nanites cosmétiques", en: "Skin that faintly glows in the dark, cosmetic nanites" },
  { fr: "Poignet cybernétique avec un écran rétractable intégré", en: "Cybernetic wrist with a built-in retractable screen" },
  { fr: "Arcade sourcilière fendue en deux endroits, mal recousue", en: "Brow ridge split in two places, poorly stitched" },
  { fr: "Bottes à semelles compensées dissimulant des lames", en: "Platform boots concealing hidden blades" },
  { fr: "Mâchoire cliquetante, prothèse dentaire cybernétique instable", en: "Clicking jaw, unstable cybernetic dental prosthesis" },
  { fr: "Tatouage de code QR sur le poignet, mène à un site mort", en: "QR code tattoo on the wrist, links to a dead site" },
  { fr: "Vieux bandeau militaire délavé noué autour du biceps", en: "Old faded military headband tied around the bicep" },
  { fr: "Dents du bonheur écartées, sourire immédiatement reconnaissable", en: "Gap-toothed smile, immediately recognizable" },
  { fr: "Cyberyeux avec enregistrement permanent, petite lumière rouge", en: "Cybereyes with permanent recording, small red light" },
  { fr: "Traces de brûlures de cigarette sur les deux avant-bras", en: "Cigarette burn marks on both forearms" },
  { fr: "Gros nez bulbeux, cassé tellement de fois qu'il est aplati", en: "Big bulbous nose, broken so many times it's flattened" },
  { fr: "Tatouage de toile d'araignée sur le coude qui s'étend au bras", en: "Spiderweb tattoo on the elbow spreading to the arm" },
  { fr: "Cheveux gras plaqués en arrière, look de requin corpo", en: "Greasy slicked-back hair, corpo shark look" },
  { fr: "Implant de filtration d'air visible dans le cou, respiration sifflante", en: "Visible air filtration implant in the neck, wheezing breath" },
  { fr: "Pied-bot cybernétique mal calibré, démarche saccadée", en: "Poorly calibrated cybernetic clubfoot, jerky gait" },
  { fr: "Micro-caméra implantée dans le lobe de l'oreille", en: "Micro-camera implanted in the earlobe" },
  { fr: "Cicatrice de trépanation cachée sous un bonnet en laine", en: "Trepanation scar hidden under a wool beanie" },
  { fr: "Bague d'acier à chaque doigt, certaines soudées en place", en: "Steel ring on every finger, some welded in place" },
  { fr: "Peau mate couverte de taches de vitiligo en forme de carte", en: "Dark skin covered in map-shaped vitiligo patches" },
  { fr: "Bras cybernétique de récupération, clairement d'occasion, rouillé", en: "Salvaged cybernetic arm, clearly second-hand, rusted" },
  { fr: "Sourire permanent figé par une paralysie faciale partielle", en: "Permanent smile frozen by partial facial paralysis" },
  { fr: "Queue préhensile biosculptée qui dépasse du manteau", en: "Biosculpted prehensile tail sticking out of the coat" },
  { fr: "Tête tatouée de flammes qui montent de la nuque au sommet du crâne", en: "Head tattooed with flames rising from nape to crown" },
  { fr: "Port USB obsolète visible derrière l'oreille, jamais retiré", en: "Obsolete USB port visible behind the ear, never removed" },
  { fr: "Nain avec une musculature de bodybuilder compressée sur un mètre vingt", en: "Dwarf with bodybuilder musculature compressed into four feet" },
  { fr: "Oeil de verre peint avec un symbole anarchiste", en: "Glass eye painted with an anarchist symbol" },
  { fr: "Pommettes hautes couvertes de taches de rousseur et de cicatrices fines", en: "High cheekbones covered in freckles and fine scars" },
  { fr: "Implant lumineux dans la paume, s'allume quand il lance un sort", en: "Luminous palm implant, lights up when casting a spell" },
  { fr: "Ceinture de munitions portée en bandoulière, plus décorative que pratique", en: "Ammo belt worn as a bandolier, more decorative than practical" },
  { fr: "Peau synthétique sur la moitié du visage, texture légèrement différente", en: "Synthetic skin on half the face, slightly different texture" },
  { fr: "Genoux cybernétiques qui craquent comme du plastique", en: "Cybernetic knees that crack like plastic" },
  { fr: "Longue natte unique jusqu'à la taille, tressée avec du fil d'acier", en: "Single long braid to the waist, woven with steel wire" },
  { fr: "Implant de communication sous-cutané, bosse visible derrière l'oreille", en: "Subcutaneous comm implant, visible bump behind the ear" },
  { fr: "Troll aux cornes asymétriques, l'une cassée à mi-longueur", en: "Troll with asymmetric horns, one broken halfway" },
  { fr: "Cicatrices chirurgicales nettes le long des bras, multiples augmentations", en: "Clean surgical scars along the arms, multiple augmentations" },
  { fr: "Foulard en kevlar noué lâchement autour du cou", en: "Kevlar scarf loosely knotted around the neck" },
  { fr: "Peau couverte de poils fins métalliques, effet secondaire d'augmentation", en: "Skin covered in fine metallic hairs, augmentation side effect" },
  { fr: "Oeil gauche en permanence injecté de sang", en: "Left eye permanently bloodshot" },
  { fr: "Implants sous-dermiques formant un motif géométrique sur le crâne", en: "Subdermal implants forming a geometric pattern on the skull" },
  { fr: "Elfe aux oreilles coupées court pour passer inaperçu", en: "Elf with ears cropped short to pass unnoticed" },
  { fr: "Vieille prothèse oculaire qui tourne parfois dans le mauvais sens", en: "Old ocular prosthesis that sometimes rotates the wrong way" },
  { fr: "Mains couvertes de tatouages de prière en japonais", en: "Hands covered in Japanese prayer tattoos" },
  { fr: "Gilet pare-balles porté à même la peau, torse nu en dessous", en: "Bulletproof vest worn against bare skin, shirtless underneath" },
  { fr: "Trous d'aération percés dans les plaques dermiques du dos", en: "Ventilation holes drilled in the dermal plates on the back" },
  { fr: "Pilosité faciale qui pousse en plaques irrégulières", en: "Facial hair growing in irregular patches" },
  { fr: "Lobe d'oreille distendu par un implant trop lourd", en: "Earlobe stretched by an implant that's too heavy" },
  { fr: "Regard fixe et sans clignement, modification oculaire", en: "Fixed unblinking stare, ocular modification" },
  { fr: "Marques de brûlure en forme d'éclair sur le bras, frappe magique", en: "Lightning-shaped burn marks on the arm, magical strike" },
  { fr: "Combinaison moulante sous un blouson trop grand", en: "Skintight bodysuit under an oversized jacket" },
  { fr: "Articulations des doigts qui craquent avec un bruit métallique", en: "Finger joints that crack with a metallic sound" },
  { fr: "Énorme cicatrice de césarienne de combat en travers du ventre", en: "Huge combat surgery scar across the belly" },
  { fr: "Visage couvert de micro-piercings en titane formant un masque", en: "Face covered in titanium micro-piercings forming a mask" },
  { fr: "Cybermonocle qui projette un réticule visible par les autres", en: "Cybermonocle projecting a reticle visible to others" },
  { fr: "Cheveux rasés sur les côtés, longs au milieu, teints en vert acide", en: "Hair shaved on the sides, long on top, dyed acid green" },
  { fr: "Morceau d'oreille manquant, bord irrégulier", en: "Missing chunk of ear, ragged edge" },
  { fr: "Poitrine marquée au fer d'un numéro de matricule militaire", en: "Chest branded with a military service number" },
  { fr: "Nain trapu avec des avant-bras aussi larges que des cuisses humaines", en: "Stocky dwarf with forearms as wide as human thighs" },
  { fr: "Yeux entièrement noirs, modification cosmétique intimidante", en: "Entirely black eyes, intimidating cosmetic modification" },
  { fr: "Vieilles bottes militaires, semelles recollées au ruban adhésif", en: "Old military boots, soles reglued with duct tape" },
  { fr: "Réseau de cicatrices sur les poignets, vestiges de ligatures", en: "Network of scars on the wrists, traces of restraints" },
  { fr: "Implant de phéromone visible comme une bosse sous la clavicule", en: "Pheromone implant visible as a bump under the collarbone" },
  { fr: "Troll avec des défenses inférieures peintes en motif damier", en: "Troll with lower tusks painted in a checkerboard pattern" },
  { fr: "Coude cybernétique à double articulation, mouvement inquiétant", en: "Double-jointed cybernetic elbow, unsettling movement" },
  { fr: "Casquette vissée sur la tête en permanence, même pour dormir", en: "Cap screwed on the head permanently, even for sleeping" },
  { fr: "Peau parcheminée et sèche, déshydratation chronique des Barrens", en: "Parchment-dry skin, chronic Barrens dehydration" },
  { fr: "Fil de suture visible le long de la mâchoire, jamais retiré", en: "Visible suture line along the jaw, never removed" },
  { fr: "Tatouage de compte à rebours sur l'avant-bras, figé à 00:03:17", en: "Countdown tattoo on the forearm, frozen at 00:03:17" },
  { fr: "Implant de ventilateur dans le cou qui s'active quand il fait chaud", en: "Fan implant in the neck that activates when it gets hot" },
  { fr: "Orc mince et élancé, défenses discrètes limées avec soin", en: "Thin and slender ork, tusks discreetly filed with care" },
  { fr: "Lèvre inférieure fendue, cicatrice en V", en: "Split lower lip, V-shaped scar" },
];

// ═══════════════════════════════════════════════════════════════
// QUIRKS — Unique behaviors, manias, obsessions
// ═══════════════════════════════════════════════════════════════

export const QUIRKS: FlavorEntry[] = [
  { fr: "Compte ses victimes à voix haute pendant les fusillades", en: "Counts kills out loud during firefights" },
  { fr: "Refuse catégoriquement de manger de la nourriture qui n'est pas rouge", en: "Absolutely refuses to eat food that isn't red" },
  { fr: "Parle à son flingue comme à un animal de compagnie", en: "Talks to their gun like a pet" },
  { fr: "Donne un nom à chaque véhicule qu'il conduit", en: "Names every vehicle they drive" },
  { fr: "Refuse d'utiliser la réalité augmentée, tout en analogique", en: "Refuses to use AR, everything analog" },
  { fr: "Ne fait jamais de run le mardi, superstition absolue", en: "Never runs on Tuesdays, absolute superstition" },
  { fr: "Collectionne les commlinks des ennemis vaincus", en: "Collects commlinks from defeated enemies" },
  { fr: "Terrorisé par les chats, panique totale en leur présence", en: "Terrified of cats, total panic in their presence" },
  { fr: "Fredonne de l'opéra pendant les fusillades", en: "Hums opera during firefights" },
  { fr: "S'excuse avant de tirer sur quelqu'un", en: "Apologizes before shooting someone" },
  { fr: "Ne fait jamais contact visuel, regarde toujours à côté", en: "Never makes eye contact, always looks away" },
  { fr: "Parle de lui-même à la troisième personne", en: "Speaks in third person about themselves" },
  { fr: "Ment toujours sur son âge, différent à chaque fois", en: "Always lies about their age, different every time" },
  { fr: "Collectionne les vieux livres en papier, les renifle régulièrement", en: "Collects old paper books, regularly sniffs them" },
  { fr: "Garde un bocal de dents prises sur ses adversaires", en: "Keeps a jar of teeth taken from opponents" },
  { fr: "Ne supporte pas le silence, met toujours de la musique", en: "Can't stand silence, always plays music" },
  { fr: "Refuse catégoriquement d'utiliser les ascenseurs", en: "Absolutely refuses to use elevators" },
  { fr: "Ne mange que du synth-sushi, considère tout autre nourriture comme barbare", en: "Only eats synth-sushi, considers all other food barbaric" },
  { fr: "Fait un rituel précis à chaque soykaf : trois tours, souffle dessus deux fois", en: "Has a precise soykaf ritual: three stirs, blows on it twice" },
  { fr: "Juge les gens selon leur commande de boisson", en: "Judges people by their drink order" },
  { fr: "Donne des conseils non sollicités sur tout, en permanence", en: "Gives unsolicited advice about everything, constantly" },
  { fr: "Porte une balle porte-bonheur autour du cou, soi-disant celle qui aurait dû le tuer", en: "Carries a lucky bullet around the neck, supposedly the one that should have killed them" },
  { fr: "N'entre jamais dans un bâtiment de 13 étages", en: "Never enters a building with 13 floors" },
  { fr: "Collectionne les patches de sécurité des corpos infiltrées", en: "Collects security patches from infiltrated corps" },
  { fr: "Amasse les vieilles puces de crédistick vides comme des trophées", en: "Hoards old empty credstick chips like trophies" },
  { fr: "Panique à la vue du sang, malgré son métier", en: "Panics at the sight of blood, despite their profession" },
  { fr: "Refuse de dormir sans musique ambient de forêt", en: "Refuses to sleep without ambient forest music" },
  { fr: "Fait craquer ses doigts cybernétiques avant chaque combat, rituel", en: "Cracks cybernetic knuckles before every fight, ritual" },
  { fr: "Cite des proverbes inventés en les attribuant à des philosophes fictifs", en: "Quotes made-up proverbs and attributes them to fictional philosophers" },
  { fr: "Refuse de tirer avec une arme qui n'a pas de nom", en: "Refuses to fire a weapon that doesn't have a name" },
  { fr: "Mange un nutribar exactement à midi, jamais une minute de plus ou de moins", en: "Eats a nutribar at exactly noon, never a minute early or late" },
  { fr: "Toujours assis dos au mur, face à la sortie", en: "Always sits with back to the wall, facing the exit" },
  { fr: "Note dans un carnet chaque personne croisée pendant un run", en: "Notes every person encountered during a run in a notebook" },
  { fr: "Refuse de courir, marche toujours, même sous les tirs", en: "Refuses to run, always walks, even under fire" },
  { fr: "Fait une prière silencieuse avant chaque combat", en: "Says a silent prayer before every fight" },
  { fr: "Mâche en permanence un cure-dent en plastique", en: "Permanently chews on a plastic toothpick" },
  { fr: "Insiste pour serrer la main après chaque deal, même aux contacts hostiles", en: "Insists on shaking hands after every deal, even with hostile contacts" },
  { fr: "Ne boit que de l'eau, considère tout autre liquide comme suspect", en: "Only drinks water, considers every other liquid suspicious" },
  { fr: "Parle aux esprits que personne d'autre ne voit, même quand il n'est pas chamane", en: "Talks to spirits no one else sees, even when not a shaman" },
  { fr: "Photographie chaque lieu de run avant et après, pour archives personnelles", en: "Photographs every run location before and after, for personal archives" },
  { fr: "Garde toujours un chargeur vide dans la poche gauche, porte-bonheur", en: "Always keeps an empty magazine in the left pocket, lucky charm" },
  { fr: "Appelle tout le monde par un surnom qu'il invente sur le coup", en: "Calls everyone by a nickname invented on the spot" },
  { fr: "Siffle le même air pendant les moments de tension", en: "Whistles the same tune during tense moments" },
  { fr: "Refuse de travailler avec quelqu'un qui porte du jaune", en: "Refuses to work with anyone wearing yellow" },
  { fr: "Collectionne les cartes de visite, même celles de ses ennemis", en: "Collects business cards, even from enemies" },
  { fr: "Lit son horoscope chaque matin et ajuste ses plans en conséquence", en: "Reads their horoscope every morning and adjusts plans accordingly" },
  { fr: "Ne dit jamais le vrai nom de quelqu'un, uniquement des périphrases", en: "Never says someone's real name, only uses circumlocutions" },
  { fr: "Nettoie ses armes compulsivement après chaque combat, pendant au moins une heure", en: "Compulsively cleans weapons after every fight, for at least an hour" },
  { fr: "Fait tourner une pièce de monnaie ancienne avant chaque décision importante", en: "Flips an ancient coin before every important decision" },
  { fr: "Refuse de traverser un pont s'il n'a pas vérifié dessous avant", en: "Refuses to cross a bridge without checking underneath first" },
  { fr: "Chantonne des berceuses quand il est nerveux", en: "Hums lullabies when nervous" },
  { fr: "Insiste pour payer en liquide, même quand c'est absurdement impratique", en: "Insists on paying cash, even when it's absurdly impractical" },
  { fr: "Garde un compte mental précis de chaque nuyen dépensé dans sa vie", en: "Keeps an exact mental tally of every nuyen spent in their life" },
  { fr: "Ne jure que par un seul fabricant d'armes, critique tous les autres", en: "Swears by only one weapons manufacturer, criticizes all others" },
  { fr: "Prend un selfie à chaque run, pour la postérité", en: "Takes a selfie at every run, for posterity" },
  { fr: "Refuse de porter des vêtements neufs, tout doit être d'occasion", en: "Refuses to wear new clothes, everything must be second-hand" },
  { fr: "Fait des origamis avec tout papier trouvé, les laisse derrière lui", en: "Makes origami from any paper found, leaves them behind" },
  { fr: "Attribue ses échecs à la malchance et ses succès à son génie", en: "Attributes failures to bad luck and successes to genius" },
  { fr: "Vérifie trois fois chaque porte avant de l'ouvrir", en: "Checks every door three times before opening it" },
  { fr: "Insiste pour être le dernier à entrer dans une pièce et le premier à en sortir", en: "Insists on being last to enter a room and first to leave" },
  { fr: "Collectionne les patchs d'unités militaires défaites", en: "Collects patches from defeated military units" },
  { fr: "Ne mange jamais le premier plat qu'on lui sert, en demande toujours un autre", en: "Never eats the first dish served, always requests another" },
  { fr: "Fait des statistiques sur tout, tient un tableur mental permanent", en: "Makes statistics about everything, keeps a permanent mental spreadsheet" },
  { fr: "Porte une alliance bien qu'il n'ait jamais été marié", en: "Wears a wedding ring despite never having been married" },
  { fr: "Range ses munitions par couleur dans ses chargeurs", en: "Sorts ammunition by color in magazines" },
  { fr: "Parle couramment une langue morte et s'énerve que personne ne la comprenne", en: "Fluently speaks a dead language and gets annoyed no one understands it" },
  { fr: "Laisse toujours un pourboire de 47%, jamais plus, jamais moins", en: "Always leaves a 47% tip, never more, never less" },
  { fr: "Refuse de manger quoi que ce soit qui contient du soja", en: "Refuses to eat anything containing soy" },
  { fr: "Tape du pied gauche cinq fois avant d'entrer en combat", en: "Taps left foot five times before entering combat" },
  { fr: "Récite la liste de ses armes comme une litanie avant de dormir", en: "Recites the list of their weapons like a litany before sleeping" },
  { fr: "Refuse de croire que la magie existe, malgré les preuves évidentes", en: "Refuses to believe magic exists, despite obvious evidence" },
  { fr: "Prend systématiquement le parti du perdant dans toute dispute", en: "Systematically sides with the underdog in every dispute" },
  { fr: "Ne parle qu'en chuchotant, même en plein combat", en: "Only speaks in whispers, even in the middle of combat" },
  { fr: "Collectionne les balles qui l'ont raté, les garde dans un sac en velours", en: "Collects bullets that missed them, keeps them in a velvet bag" },
  { fr: "Fait des mots croisés pendant les planques, ignore les briefings", en: "Does crosswords during stakeouts, ignores briefings" },
  { fr: "Prétend avoir un frère jumeau identique pour justifier ses contradictions", en: "Claims to have an identical twin to justify contradictions" },
  { fr: "Refuse de manger si la nourriture n'est pas disposée de façon symétrique dans l'assiette", en: "Refuses to eat if food isn't arranged symmetrically on the plate" },
  { fr: "Chronométre absolument tout, du trajet au temps de recharge", en: "Times absolutely everything, from travel to reload time" },
  { fr: "Garde une photo d'un inconnu dans son portefeuille et prétend que c'est son mentor", en: "Keeps a photo of a stranger in their wallet and claims it's their mentor" },
  { fr: "Tousse de façon très théâtrale après chaque mensonge", en: "Coughs very theatrically after every lie" },
  { fr: "Ne quitte jamais une pièce sans emporter un petit objet en souvenir", en: "Never leaves a room without taking a small object as a souvenir" },
  { fr: "Refuse de s'asseoir sur une chaise qui a déjà été utilisée par quelqu'un d'autre", en: "Refuses to sit in a chair that someone else has already used" },
  { fr: "Invente des acronymes pour tout et s'attend à ce que tout le monde les connaisse", en: "Invents acronyms for everything and expects everyone to know them" },
  { fr: "Recoud lui-même ses blessures au lieu d'aller voir un doc de rue", en: "Stitches up their own wounds instead of seeing a street doc" },
  { fr: "Considère chaque run comme un épisode de sa propre série trid", en: "Considers every run as an episode of their own trid series" },
  { fr: "Dort toujours avec un couteau sous l'oreiller, même chez des amis", en: "Always sleeps with a knife under the pillow, even at friends' places" },
  { fr: "Ne mange que des aliments en nombre impair sur l'assiette", en: "Only eats food in odd numbers on the plate" },
  { fr: "Fait un résumé narratif de la situation à personne en particulier", en: "Gives a narrative summary of the situation to no one in particular" },
  { fr: "Classe les gens en catégories animales et les traite en conséquence", en: "Classifies people into animal categories and treats them accordingly" },
  { fr: "Garde un journal intime dicté à son commlink pendant les runs", en: "Keeps a diary dictated to their commlink during runs" },
  { fr: "N'utilise que des expressions des années 2020, refuse l'argot moderne", en: "Only uses 2020s expressions, refuses modern slang" },
  { fr: "Touche du bois avant chaque run, paniqué s'il n'y a pas de bois", en: "Knocks on wood before every run, panics if there's no wood" },
  { fr: "Insiste pour que chaque membre de l'équipe ait un rôle de film d'action", en: "Insists every team member have an action movie role" },
  { fr: "Entretient une conversation avec une IA disparue depuis des années", en: "Maintains a conversation with an AI that disappeared years ago" },
  { fr: "Ne porte que du noir et appelle ça de la stratégie", en: "Only wears black and calls it strategy" },
  { fr: "Lance une pièce pour décider entre la porte de gauche et celle de droite", en: "Flips a coin to choose between the left door and the right door" },
  { fr: "Refuse de partager un véhicule avec plus de trois personnes", en: "Refuses to share a vehicle with more than three people" },
  { fr: "Dit 'pour la science' avant de faire quelque chose de stupide", en: "Says 'for science' before doing something stupid" },
  { fr: "Envoie un message d'adieu à un contact différent avant chaque run", en: "Sends a farewell message to a different contact before each run" },
  { fr: "Garde un décompte des faveurs dues et rendues sur un fichier chiffré", en: "Keeps a tally of favors owed and returned in an encrypted file" },
  { fr: "Insiste pour que tout le monde utilise des noms de code même au bar", en: "Insists everyone uses code names even at the bar" },
  { fr: "Fait un discours de motivation avant chaque combat, que ça plaise ou non", en: "Gives a motivational speech before every fight, like it or not" },
  { fr: "Mange le dessert en premier parce qu'on ne sait jamais si on va survivre", en: "Eats dessert first because you never know if you'll survive" },
  { fr: "Refuse de porter une arme qui n'a pas au moins un accessoire esthétique", en: "Refuses to carry a weapon without at least one cosmetic accessory" },
  { fr: "Salue les caméras de surveillance en passant devant", en: "Salutes surveillance cameras when passing by" },
  { fr: "Ne finit jamais une phrase, laisse toujours en suspens...", en: "Never finishes a sentence, always leaves it hanging..." },
  { fr: "A un classement personnel des meilleurs johnsons, le met à jour régulièrement", en: "Has a personal ranking of best Johnsons, updates it regularly" },
  { fr: "Insiste pour vérifier la sortie de secours avant de s'asseoir quelque part", en: "Insists on checking the emergency exit before sitting anywhere" },
  { fr: "Porte un masque à gaz autour du cou même quand l'air est pur", en: "Wears a gas mask around the neck even when the air is clean" },
  { fr: "Surnomme chaque run et y fait référence comme à des campagnes militaires", en: "Nicknames every run and refers to them like military campaigns" },
  { fr: "Refuse d'utiliser une arme dont le numéro de série contient un 4", en: "Refuses to use a weapon whose serial number contains a 4" },
  { fr: "Se brosse les dents trois fois de suite après chaque repas", en: "Brushes teeth three times in a row after every meal" },
  { fr: "Parle aux machines comme si elles avaient des sentiments", en: "Talks to machines as if they have feelings" },
  { fr: "Sifflote l'hymne d'une corp qu'il déteste, sans s'en rendre compte", en: "Whistles the anthem of a corp they hate, without realizing it" },
  { fr: "Garde un caillou ramassé sur chaque lieu de run", en: "Keeps a pebble picked up from every run location" },
  { fr: "Refuse de boire un verre qui a été posé hors de sa vue, même une seconde", en: "Refuses to drink from a glass left out of sight, even for a second" },
  { fr: "Organise les chargeurs par ordre alphabétique des fabricants", en: "Organizes magazines in alphabetical order by manufacturer" },
  { fr: "Raconte la même anecdote de guerre à chaque nouveau coéquipier", en: "Tells the same war story to every new teammate" },
  { fr: "Envoie des rapports de mission détaillés à personne", en: "Sends detailed mission reports to no one" },
  { fr: "Insiste pour écouter du jazz pendant la planification, dit que ça aide à penser", en: "Insists on listening to jazz during planning, says it helps thinking" },
  { fr: "Gratte une pièce de monnaie entre les doigts quand il est stressé", en: "Scratches a coin between fingers when stressed" },
  { fr: "Refuse de serrer la main de quelqu'un dont il ne connaît pas le signe astrologique", en: "Refuses to shake hands with someone whose zodiac sign they don't know" },
  { fr: "Murmure 'c'est une embuscade' en entrant dans chaque pièce", en: "Whispers 'it's an ambush' when entering every room" },
  { fr: "Ne boit que dans son propre mug, le lave avec un soin maniaque", en: "Only drinks from their own mug, washes it with manic care" },
  { fr: "Dessine un plan de chaque pièce visitée sur un carnet", en: "Draws a floor plan of every room visited in a notebook" },
  { fr: "Se présente avec un titre inventé différent à chaque rencontre", en: "Introduces themselves with a different made-up title at each meeting" },
  { fr: "Porte un gilet de sauvetage sous son armure, au cas où", en: "Wears a life vest under their armor, just in case" },
  { fr: "Refuse catégoriquement les runs qui impliquent des sous-sols", en: "Absolutely refuses runs involving basements" },
  { fr: "Fait un check-up médical complet après chaque run, même sans blessure", en: "Does a full medical check-up after every run, even without injury" },
  { fr: "Conserve les étiquettes de prix de toutes ses armes", en: "Keeps the price tags of all their weapons" },
  { fr: "Demande toujours une estimation de la valeur en nuyens de chaque objet rencontré", en: "Always asks for a nuyen estimate of every object encountered" },
  { fr: "Parle en code même quand c'est totalement inutile", en: "Speaks in code even when it's totally unnecessary" },
  { fr: "Insiste pour donner un briefing, même quand il n'est pas le chef", en: "Insists on giving a briefing even when not the leader" },
  { fr: "Enregistre chaque conversation, 'pour des raisons légales'", en: "Records every conversation, 'for legal reasons'" },
  { fr: "Ne mange jamais au même endroit deux fois de suite", en: "Never eats at the same place twice in a row" },
  { fr: "Fait des blagues de papa au pire moment possible", en: "Makes dad jokes at the worst possible moment" },
  { fr: "Refuse de prendre un taxi conduit par un humain, préfère les drones", en: "Refuses to take a human-driven taxi, prefers drones" },
  { fr: "Garde un compte de toutes les portes qu'il a défoncées dans sa carrière", en: "Keeps a count of every door kicked down in their career" },
  { fr: "Nettoie sa place à table avec une lingette avant de s'asseoir", en: "Wipes down their place at the table before sitting" },
  { fr: "Porte un vêtement d'un camarade tombé au combat, refuse de l'enlever", en: "Wears a garment from a fallen comrade, refuses to take it off" },
  { fr: "Donne une note sur dix à chaque plan de run proposé", en: "Rates every proposed run plan out of ten" },
  { fr: "Fait une sieste de précisément sept minutes avant chaque run", en: "Takes a nap of precisely seven minutes before every run" },
  { fr: "Invente un cri de guerre différent à chaque combat", en: "Invents a different battle cry for every fight" },
  { fr: "Refuse de courir sous la pluie, convaincu que l'eau de pluie est toxique", en: "Refuses to run in the rain, convinced rainwater is toxic" },
  { fr: "Plie ses vêtements avec une précision militaire, même sur le terrain", en: "Folds clothes with military precision, even in the field" },
  { fr: "Ne commence jamais une conversation, attend toujours que l'autre parle en premier", en: "Never starts a conversation, always waits for the other person to speak first" },
  { fr: "Parie sur l'issue de chaque combat avec un coéquipier imaginaire", en: "Bets on the outcome of every fight with an imaginary teammate" },
  { fr: "Demande le groupe sanguin de chaque nouveau contact", en: "Asks for the blood type of every new contact" },
  { fr: "Garde la dernière balle de chaque chargeur et ne l'utilise jamais", en: "Keeps the last bullet from every magazine and never uses it" },
  { fr: "Chante du death metal quand il pirate un système", en: "Sings death metal while hacking a system" },
  { fr: "Refuse de passer par une porte ouverte, doit l'ouvrir lui-même", en: "Refuses to walk through an open door, must open it themselves" },
  { fr: "Chronométre la durée exacte de chaque run et optimise mentalement", en: "Times the exact duration of each run and mentally optimizes" },
  { fr: "N'achète que des armes de seconde main, dit que ça porte chance", en: "Only buys second-hand weapons, says it brings luck" },
  { fr: "Récite un haïku avant chaque prise de décision critique", en: "Recites a haiku before every critical decision" },
  { fr: "Prétend que chaque lieu est hanté et s'adresse aux fantômes", en: "Claims every location is haunted and addresses the ghosts" },
  { fr: "Garde un classeur de fiches sur chaque fixer rencontré", en: "Keeps a binder of files on every fixer encountered" },
  { fr: "Ne se déplace qu'à droite dans les couloirs, jamais au milieu", en: "Only walks on the right side of corridors, never in the middle" },
  { fr: "Donne un surnom à chaque blessure reçue", en: "Gives a nickname to every wound received" },
  { fr: "Refuse les poignées de porte rondes, n'ouvre que les poignées plates", en: "Refuses round door knobs, only opens flat handles" },
  { fr: "Fait une minute de silence pour chaque ennemi tué, retarde souvent le groupe", en: "Holds a minute of silence for every enemy killed, often delays the group" },
  { fr: "Ne dort que dans des endroits en hauteur, toits, mezzanines, passerelles", en: "Only sleeps in elevated places: rooftops, mezzanines, catwalks" },
  { fr: "Dessine un smiley sur chaque mur après un combat réussi", en: "Draws a smiley face on every wall after a successful fight" },
  { fr: "Conserve les menus de tous les restaurants où il a mangé", en: "Keeps the menus from every restaurant where they've eaten" },
  { fr: "Considère les grenades comme des solutions universelles à tous les problèmes", en: "Considers grenades a universal solution to every problem" },
  { fr: "Ne boit son soykaf qu'à une température très précise, vérifie au thermomètre", en: "Only drinks soykaf at a very precise temperature, checks with a thermometer" },
  { fr: "Refuse de regarder les explosions, se retourne toujours", en: "Refuses to look at explosions, always turns away" },
  { fr: "Appelle chaque planque 'la base secrète' avec un sérieux absolu", en: "Calls every safehouse 'the secret base' with absolute seriousness" },
  { fr: "Mâchonne les câbles de données quand il réfléchit", en: "Chews on data cables when thinking" },
  { fr: "Refuse de manger de la viande synthétique le vendredi", en: "Refuses to eat synthetic meat on Fridays" },
  { fr: "Insulte ses adversaires avec des injures archaïques du XVIIIe siècle", en: "Insults opponents with archaic 18th century profanity" },
  { fr: "Prend des notes sur le style de combat de chaque ennemi pour un livre qu'il écrit", en: "Takes notes on every enemy's fighting style for a book they're writing" },
  { fr: "Garde un pot de terre de sa ville natale dans sa poche, le touche pour se rassurer", en: "Keeps a pot of soil from their hometown in their pocket, touches it for comfort" },
  { fr: "Attribue chaque réussite à un ami imaginaire appelé 'El Capitán'", en: "Attributes every success to an imaginary friend called 'El Capitán'" },
  { fr: "Retourne les miroirs dans chaque pièce où il entre", en: "Turns mirrors around in every room they enter" },
  { fr: "Renifle les gens pour les juger, prétend sentir la trahison", en: "Sniffs people to judge them, claims to smell betrayal" },
  { fr: "Refuse tout plan qui ne contient pas au moins une diversion", en: "Refuses any plan that doesn't include at least one diversion" },
  { fr: "Vérifie sa montre toutes les deux minutes exactement", en: "Checks their watch every two minutes exactly" },
  { fr: "Fait un discours d'adieu avant chaque combat comme si c'était le dernier", en: "Gives a farewell speech before every fight as if it's the last" },
  { fr: "Tape un rythme complexe sur la table quand il attend", en: "Taps a complex rhythm on the table while waiting" },
  { fr: "Refuse de traverser un carrefour sans regarder dans les six directions", en: "Refuses to cross an intersection without looking in all six directions" },
  { fr: "Porte un cure-oreille en ivoire synthétique et s'en sert en public", en: "Carries a synthetic ivory ear pick and uses it in public" },
  { fr: "Garde une liste de toutes les personnes qui lui doivent de l'argent, mise à jour quotidienne", en: "Keeps a list of everyone who owes them money, updated daily" },
  { fr: "Confond volontairement les noms des gens pour les déstabiliser", en: "Deliberately confuses people's names to throw them off" },
  { fr: "Refuse de manger quoi que ce soit qui ne vient pas d'un distributeur automatique", en: "Refuses to eat anything that doesn't come from a vending machine" },
  { fr: "Demande un reçu après chaque run, même aux fixers", en: "Asks for a receipt after every run, even from fixers" },
  { fr: "Fait le signe de croix inversé en voyant un drone de sécurité", en: "Makes an inverted sign of the cross when seeing a security drone" },
  { fr: "Conserve un enregistrement de chaque coucher de soleil depuis trois ans", en: "Has recorded every sunset for the past three years" },
  { fr: "Compte les marches de chaque escalier à voix haute", en: "Counts the steps of every staircase out loud" },
  { fr: "Refuse de donner son nom, répond 'tu sais qui je suis' à chaque fois", en: "Refuses to give their name, answers 'you know who I am' every time" },
  { fr: "S'arrête pour caresser chaque chien croisé, même en pleine fuite", en: "Stops to pet every dog encountered, even during an escape" },
  { fr: "Garde un petit carnet où il note les derniers mots de ses ennemis", en: "Keeps a small notebook recording enemies' last words" },
  { fr: "Insiste pour commander la boisson la plus compliquée du menu", en: "Insists on ordering the most complicated drink on the menu" },
  { fr: "Ne se bat qu'avec des gants, dit que le sang tache trop", en: "Only fights wearing gloves, says blood stains too much" },
  { fr: "Collectionne les stylos des gens qu'il rencontre, s'en vante ouvertement", en: "Collects pens from people they meet, brags openly about it" },
  { fr: "Refuse de dormir dans un lit, ne dort que dans des hamacs ou par terre", en: "Refuses to sleep in a bed, only sleeps in hammocks or on the floor" },
  { fr: "Fait un origami de grue à chaque contact tué, les empile dans une boîte", en: "Folds an origami crane for every contact killed, stacks them in a box" },
  { fr: "Marmonne des équations mathématiques sous pression", en: "Mumbles math equations under pressure" },
  { fr: "Exige un silence total de trente secondes avant chaque briefing", en: "Demands thirty seconds of total silence before every briefing" },
  { fr: "Porte toujours deux montres, une à chaque poignet, réglées sur des fuseaux différents", en: "Always wears two watches, one on each wrist, set to different time zones" },
  { fr: "Fait un clin d'oeil après chaque phrase, même les plus graves", en: "Winks after every sentence, even the most serious ones" },
];
