/**
 * NPC Flavor Data — Part 3: Fetish Objects
 * Bilingual flavor text tables for procedural NPC generation.
 * Each entry is a unique iconic personal item a runner always carries.
 */

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

/** Bilingual flavor entry */
export interface FlavorEntry { fr: string; en: string; }

// ═══════════════════════════════════════════════════════════════
// FETISH OBJECTS — Iconic personal items every runner carries
// ═══════════════════════════════════════════════════════════════

export const FETISH_OBJECTS: FlavorEntry[] = [
  // ——— Sentimental items ———
  { fr: "Un zippo gravé avec les mots 'Ne fais confiance à personne' en japonais", en: "A zippo engraved with 'Trust no one' in Japanese" },
  { fr: "Une vieille photo Polaroid tellement usée qu'on ne voit plus le visage dessus", en: "An old Polaroid photo so worn you can't see the face anymore" },
  { fr: "L'alliance d'un mariage qui n'a jamais eu lieu, portée à une chaîne autour du cou", en: "A wedding ring from a marriage that never happened, worn on a chain around their neck" },
  { fr: "Un dessin d'enfant représentant une famille devant une maison, plié en huit", en: "A child's drawing of a family in front of a house, folded into eighths" },
  { fr: "La dernière lettre manuscrite de leur mère, scellée et jamais rouverte", en: "The last handwritten letter from their mother, sealed and never reopened" },
  { fr: "Un médaillon contenant une mèche de cheveux blancs dont ils refusent de parler", en: "A locket containing a lock of white hair they refuse to discuss" },
  { fr: "Un petit ours en peluche brûlé sur un côté, rescapé d'un incendie de Barrens", en: "A small teddy bear burned on one side, rescued from a Barrens fire" },
  { fr: "Une carte postale de Seattle datée d'avant le Crash 2.0, jamais envoyée", en: "A postcard from Seattle dated before Crash 2.0, never sent" },
  { fr: "Le badge d'employé Renraku de leur père, taché de sang séché", en: "Their father's Renraku employee badge, stained with dried blood" },
  { fr: "Un origami en forme de grue fait par leur petite sœur le jour de sa disparition", en: "An origami crane made by their little sister the day she disappeared" },
  { fr: "Une clé USB contenant la voix de quelqu'un qu'ils ont perdu, jamais réécoutée", en: "A USB drive containing the voice of someone they lost, never replayed" },
  { fr: "Un bracelet tressé à deux couleurs, l'autre moitié portée par quelqu'un de mort", en: "A two-color braided bracelet, the other half worn by someone now dead" },
  { fr: "Une minuscule boîte à musique jouant un air que personne d'autre ne reconnaît", en: "A tiny music box playing a tune nobody else recognizes" },
  { fr: "Un morceau de tissu découpé dans la couverture de leur bébé, toujours dans leur poche", en: "A scrap of fabric cut from their baby blanket, always in their pocket" },
  { fr: "La montre de leur grand-père, arrêtée à 3h17, l'heure exacte de sa mort", en: "Their grandfather's watch, stopped at 3:17 AM, the exact time of his death" },
  { fr: "Un collier de perles en plastique offert par un enfant des Barrens qu'ils n'ont pas pu sauver", en: "A plastic bead necklace given by a Barrens kid they couldn't save" },
  { fr: "Une lettre d'amour écrite en or'zet, pliée si souvent que les mots s'effacent", en: "A love letter written in Or'zet, folded so often the words are fading" },
  { fr: "Le premier credstick qu'on leur a donné à l'orphelinat, valeur : 0 nuyen", en: "The first credstick they were given at the orphanage, balance: 0 nuyen" },
  { fr: "Un petit carnet rempli de noms barrés — tous des gens qu'ils ont perdus", en: "A small notebook full of crossed-out names — all people they've lost" },
  { fr: "Un bouton de manchette Ares arraché du costume de leur père lors de leur dernière dispute", en: "An Ares cufflink torn from their father's suit during their last argument" },

  // ——— Lucky charms ———
  { fr: "Un dé à six faces en os de dragon, toujours dans sa poche gauche", en: "A six-sided die made from dragon bone, always in their left pocket" },
  { fr: "Une balle de calibre .50 qui les a ratés de trois centimètres, montée en pendentif", en: "A .50 caliber bullet that missed them by three centimeters, mounted as a pendant" },
  { fr: "Une patte de lapin provenant d'un lapin Éveillé, brillant faiblement la nuit", en: "A rabbit's foot from an Awakened rabbit, glowing faintly at night" },
  { fr: "Un credstick avec exactement 1¥ dessus qu'ils n'ont jamais dépensé", en: "A credstick with exactly 1¥ on it they've never spent" },
  { fr: "Un jeton de poker volé à un dragon lors d'une partie clandestine", en: "A poker chip stolen from a dragon during an underground game" },
  { fr: "Une pièce de monnaie pré-Éveil qu'ils font tourner avant chaque run", en: "A pre-Awakening coin they spin before every run" },
  { fr: "Un trèfle à quatre feuilles plastifié, trouvé dans une zone toxique", en: "A laminated four-leaf clover found in a toxic zone" },
  { fr: "Un fragment de balle logé dans un médaillon — celle qui aurait dû les tuer", en: "A bullet fragment set in a medallion — the one that should have killed them" },
  { fr: "Un petit crâne en chrome qu'ils frottent avant chaque combat", en: "A small chrome skull they rub before every fight" },
  { fr: "Un dé pipé qui tombe toujours sur le six, trouvé sur un cadavre chanceux", en: "A loaded die that always lands on six, found on a lucky corpse" },
  { fr: "Un éclat de miroir qu'ils prétendent voir l'avenir dedans quand la lumière est bonne", en: "A mirror shard they claim shows the future when the light is right" },
  { fr: "Un ticket de loterie gagnant non réclamé datant de 2049", en: "An unclaimed winning lottery ticket from 2049" },
  { fr: "Un petit sachet de sel béni par un chaman qu'ils gardent dans leur botte droite", en: "A small pouch of salt blessed by a shaman, kept in their right boot" },
  { fr: "Un ongle de troll incassable porté en amulette autour du cou", en: "An unbreakable troll fingernail worn as an amulet around their neck" },
  { fr: "Un vieux jeton de métro de Seattle qu'ils font tourner entre leurs doigts quand ils réfléchissent", en: "An old Seattle metro token they spin between their fingers when thinking" },

  // ——— Trophies ———
  { fr: "Les plaques militaires de leur première cible, jamais nettoyées", en: "The dog tags of their first kill, never cleaned" },
  { fr: "Un bouton de manchette en platine d'un cadre Aztechnology qu'ils ont descendu", en: "A platinum cufflink from an Aztechnology executive they took down" },
  { fr: "Un morceau du blindage d'un drone Ares qu'ils ont détruit à mains nues", en: "A piece of armor plating from an Ares drone they destroyed bare-handed" },
  { fr: "Une dent en or arrachée à un rival lors de leur premier combat de rue", en: "A gold tooth pulled from a rival during their first street fight" },
  { fr: "L'insigne d'un officier Lone Star qu'ils ont laissé en vie, comme rappel", en: "The badge of a Lone Star officer they left alive, as a reminder" },
  { fr: "Un morceau de fibre optique arraché d'un nœud de la Matrice qu'ils ont crashé", en: "A length of fiber optic cable torn from a Matrix node they crashed" },
  { fr: "Le stylo Montblanc d'un Johnson qui a essayé de les doubler", en: "The Montblanc pen of a Johnson who tried to double-cross them" },
  { fr: "Un patch d'unité des Tir Ghost arraché lors d'une embuscade dans la forêt", en: "A Tir Ghost unit patch torn off during a forest ambush" },
  { fr: "La lame cassée du premier couteau qu'ils ont planté dans quelqu'un", en: "The broken blade of the first knife they stuck in someone" },
  { fr: "Un œil cybernétique désactivé pris à un adversaire, gardé dans un petit bocal", en: "A deactivated cybernetic eye taken from an opponent, kept in a small jar" },
  { fr: "Un morceau de la corne d'un esprit du feu qu'ils ont banni", en: "A piece of horn from a fire spirit they banished" },
  { fr: "La carte d'accès d'un laboratoire Mitsuhama qu'ils ont fait exploser", en: "The access card to a Mitsuhama lab they blew up" },
  { fr: "Un éclat de verre blindé provenant du bureau d'un CEO de Saeder-Krupp", en: "A shard of armored glass from a Saeder-Krupp CEO's office" },
  { fr: "Un bout de fil barbelé du camp dont ils se sont évadés dans les Barrens", en: "A length of barbed wire from the camp they escaped in the Barrens" },
  { fr: "Le dernier message d'erreur d'une IA qu'ils ont tuée, imprimé sur papier thermique", en: "The last error message of an AI they killed, printed on thermal paper" },

  // ——— Weird collections ———
  { fr: "Un bocal contenant sept datajacks extraits, étiquetés avec des dates", en: "A jar containing seven extracted datajacks, labeled with dates" },
  { fr: "Un sac en toile rempli de grues en origami — une pour chaque personne qu'ils ont tuée", en: "A canvas bag full of origami cranes — one for each person they've killed" },
  { fr: "Une collection de dents de différentes métaespèces dans un étui à cigares", en: "A collection of teeth from different metatypes in a cigar case" },
  { fr: "Un trousseau de clés dont aucune n'ouvre plus rien, mais ils les gardent quand même", en: "A keyring of keys that no longer open anything, but they keep them anyway" },
  { fr: "Un carnet rempli de croquis de chaque endroit où ils ont failli mourir", en: "A notebook filled with sketches of every place they almost died" },
  { fr: "Treize billes de verre de couleurs différentes dans une pochette en cuir", en: "Thirteen glass marbles of different colors in a leather pouch" },
  { fr: "Un sachet de puces RFID grillées récupérées sur des corps au fil des années", en: "A pouch of fried RFID chips collected from bodies over the years" },
  { fr: "Une boîte de boutons dépareillés arrachés aux vêtements de leurs victimes", en: "A box of mismatched buttons torn from their victims' clothing" },
  { fr: "Un album photo rempli de clichés de lieux abandonnés du Sixième Monde", en: "A photo album filled with pictures of abandoned Sixth World locations" },
  { fr: "Un fil sur lequel sont enfilées des capsules de balles aplaties comme des perles", en: "A string threaded with flattened bullet casings like beads" },
  { fr: "Un petit classeur contenant des cartes de visite de tous les fixers qu'ils ont connus", en: "A small binder containing business cards from every fixer they've known" },
  { fr: "Sept petites fioles contenant de la terre de sept pays différents", en: "Seven small vials containing soil from seven different countries" },

  // ——— Old world relics ———
  { fr: "Un smartphone pré-Éveil avec un écran fissuré, batterie morte depuis des décennies", en: "A pre-Awakening smartphone with a cracked screen, battery dead for decades" },
  { fr: "Un livre de poche en papier — un roman policier dont il manque les dix dernières pages", en: "A paper paperback — a mystery novel missing the last ten pages" },
  { fr: "Un vinyle de jazz analogique qu'ils n'ont aucun moyen de lire", en: "An analog jazz vinyl record they have no way to play" },
  { fr: "Une montre mécanique suisse qui retarde de trois minutes par jour", en: "A Swiss mechanical watch that loses three minutes every day" },
  { fr: "Un appareil photo argentique avec une seule photo non développée sur le rouleau", en: "A film camera with one undeveloped photo left on the roll" },
  { fr: "Un walkman cassette fonctionnel avec un seul album chargé qu'ils écoutent en boucle", en: "A working cassette Walkman with one album loaded that they play on repeat" },
  { fr: "Un jeu de cartes à jouer en papier, il en manque le valet de pique", en: "A paper deck of playing cards, missing the jack of spades" },
  { fr: "Un stylo-plume à encre véritable, une relique d'avant l'ère numérique", en: "A fountain pen with real ink, a relic from before the digital age" },
  { fr: "Un globe terrestre miniature montrant les frontières d'avant le Réveil", en: "A miniature globe showing pre-Awakening national borders" },
  { fr: "Un dictionnaire papier français-japonais tenu par un élastique", en: "A paper French-Japanese dictionary held together with a rubber band" },
  { fr: "Un Rubik's Cube original des années 80, résolu et collé en place", en: "An original 1980s Rubik's Cube, solved and glued in place" },
  { fr: "Un briquet Zippo en laiton qui fonctionne encore, alimenté à l'essence véritable", en: "A brass Zippo lighter that still works, fueled with real gasoline" },
  { fr: "Une paire de lunettes de soleil Ray-Ban vintage, un verre félé", en: "A pair of vintage Ray-Ban sunglasses, one lens cracked" },
  { fr: "Une cassette VHS étiquetée 'NE PAS REGARDER' en lettres majuscules", en: "A VHS tape labeled 'DO NOT WATCH' in block letters" },
  { fr: "Un tamagotchi pré-Éveil dont la créature virtuelle est morte depuis 2030", en: "A pre-Awakening Tamagotchi whose virtual pet has been dead since 2030" },

  // ——— Tech items ———
  { fr: "Un commlink briqué lors de leur premier run, qu'ils portent en bracelet", en: "A commlink bricked during their first run, worn as a bracelet" },
  { fr: "Une puce de données peinte à la main avec un motif de flammes aztech", en: "A data chip custom-painted with an Aztech flame pattern" },
  { fr: "Le module mémoire central d'une IA morte qu'ils jurent entendre murmurer parfois", en: "The core memory module of a dead AI they swear they hear whispering sometimes" },
  { fr: "Un œil cybernétique de rechange qu'ils gardent 'au cas où', roulant dans leur poche", en: "A spare cybernetic eye they keep 'just in case', rolling around in their pocket" },
  { fr: "Un vieux câble de datajack enroulé comme un bracelet autour de leur poignet", en: "An old datajack cable coiled like a bracelet around their wrist" },
  { fr: "Un circuit imprimé arraché au premier drone qu'ils ont hacké, monté en broche", en: "A circuit board ripped from the first drone they hacked, mounted as a brooch" },
  { fr: "Un holoprojecteur miniature affichant en boucle trois secondes d'un coucher de soleil", en: "A miniature holographic projector looping three seconds of a sunset" },
  { fr: "Une diode LED clignotante sans alimentation, récupérée dans les ruines de Renraku Arcology", en: "A blinking LED with no power source, salvaged from the Renraku Arcology ruins" },
  { fr: "Un disque dur magnétique d'un téraoctet, énorme et obsolète, utilisé comme presse-papier", en: "A one-terabyte magnetic hard drive, enormous and obsolete, used as a paperweight" },
  { fr: "Un drone espion miniature désactivé qu'ils appellent 'Petit' et à qui ils parlent", en: "A deactivated miniature spy drone they call 'Little One' and talk to" },
  { fr: "Un écran flexible enroulable affichant un message d'erreur permanent en néon vert", en: "A rollable flex-screen displaying a permanent error message in neon green" },
  { fr: "Une carte mère de commlink gravée avec les initiales de toute leur ancienne équipe", en: "A commlink motherboard engraved with the initials of their old team" },
  { fr: "Un fragment de satellite tombé qu'ils prétendent être d'origine extraterrestre", en: "A piece of fallen satellite they claim is of extraterrestrial origin" },
  { fr: "Un implant sous-cutané retiré de leur propre bras, conservé dans de la résine", en: "A subdermal implant removed from their own arm, preserved in resin" },

  // ——— Magical objects ———
  { fr: "Une plume d'aigle Éveillé qui flotte légèrement quand on la lâche", en: "A feather from an Awakened eagle that floats slightly when released" },
  { fr: "Un cristal de quartz qui brille faiblement en présence de magie", en: "A quartz crystal that glows faintly in the presence of magic" },
  { fr: "Une fiole d'eau imprégnée de mana récoltée dans un lac sacré amérindien", en: "A vial of mana-infused water collected from a sacred Amerindian lake" },
  { fr: "Un petit caillou ramassé dans un cercle de menhirs en Écosse, chaud au toucher", en: "A small pebble picked up from a stone circle in Scotland, warm to the touch" },
  { fr: "Un éclat d'os de sasquatch gravé de runes qu'aucun chamane ne sait déchiffrer", en: "A Sasquatch bone fragment carved with runes no shaman can decipher" },
  { fr: "Un flacon d'encre de calmar Éveillé qui change de couleur selon l'humeur du porteur", en: "A vial of Awakened squid ink that changes color based on the bearer's mood" },
  { fr: "Une bague en bois pétrifié provenant d'un arbre du Lacplesis, au Tir Tairngire", en: "A ring of petrified wood from a Lacplesis tree in Tir Tairngire" },
  { fr: "Un petit sablier dont le sable coule parfois vers le haut", en: "A small hourglass whose sand sometimes flows upward" },
  { fr: "Un scarabée en ambre contenant un insecte Éveillé fossilisé qui semble bouger la nuit", en: "An amber scarab containing a fossilized Awakened insect that seems to move at night" },
  { fr: "Un galet de rivière couvert de mousse qui ne meurt jamais et ne pousse jamais", en: "A river stone covered in moss that never dies and never grows" },
  { fr: "Un bout de charbon ardent perpétuel, enveloppé dans un tissu ignifugé", en: "A perpetually burning piece of charcoal, wrapped in fireproof cloth" },
  { fr: "Un miroir de poche en obsidienne qui ne reflète jamais tout à fait la réalité", en: "An obsidian pocket mirror that never quite reflects reality" },
  { fr: "Une petite clochette en argent dont le son n'est audible que par les Éveillés", en: "A small silver bell whose sound is only audible to the Awakened" },
  { fr: "Un croc de loup Éveillé monté en pendentif qui vibre quand le danger approche", en: "An Awakened wolf fang mounted as a pendant that vibrates when danger approaches" },
  { fr: "Un gland de chêne d'un bosquet sacré qui refuse de germer malgré tous les efforts", en: "An acorn from a sacred grove that refuses to sprout despite all efforts" },

  // ——— Food/drink ———
  { fr: "Un paquet de cigarettes pré-Éveil qu'ils refusent de fumer ou de jeter", en: "A pack of pre-Awakening cigarettes they refuse to smoke or throw away" },
  { fr: "Une flasque de vrai whisky écossais qu'ils n'ouvrent jamais, gardée pour 'le bon moment'", en: "A flask of real Scotch whisky they never open, saved for 'the right moment'" },
  { fr: "Un bonbon au caramel dans son emballage d'origine, durci comme une pierre depuis dix ans", en: "A caramel candy in its original wrapper, hardened like a rock for ten years" },
  { fr: "Un sachet de vrai thé Earl Grey, le dernier d'une boîte offerte par un ami mort", en: "A bag of real Earl Grey tea, the last from a box given by a dead friend" },
  { fr: "Une canette de Coca-Cola vintage non ouverte de 2029, légèrement bosselée", en: "An unopened vintage 2029 Coca-Cola can, slightly dented" },
  { fr: "Un flacon de sauce piquante artisanale fabriquée par un troll cuisinier de Redmond", en: "A bottle of artisanal hot sauce made by a troll cook from Redmond" },
  { fr: "Un morceau de chocolat suisse sous vide qu'ils reniflent parfois sans jamais l'ouvrir", en: "A vacuum-sealed piece of Swiss chocolate they sometimes sniff but never open" },
  { fr: "Une gourde militaire remplie d'eau de source 'pure', jamais bue, de peur qu'elle soit la dernière", en: "A military canteen full of 'pure' spring water, never drunk, afraid it's the last" },
  { fr: "Un petit pot de vrai miel cristallisé, volé lors d'un run dans une ferme corpo", en: "A small jar of real crystallized honey, stolen during a run on a corpo farm" },
  { fr: "Un biscuit de ration militaire qu'ils gardent comme 'dernier repas' depuis cinq ans", en: "A military ration biscuit they've kept as their 'last meal' for five years" },

  // ——— Clothing/accessories ———
  { fr: "Une écharpe tricotée par leur mère, trouée par deux impacts de balles", en: "A scarf knitted by their mother, with two bullet holes in it" },
  { fr: "Des gants mitaines en cuir usé offerts par leur mentor le jour de leur premier run", en: "Worn leather fingerless gloves given by their mentor the day of their first run" },
  { fr: "Un chapeau fedora noir dont ils refusent catégoriquement d'expliquer l'origine", en: "A black fedora hat whose origin they categorically refuse to explain" },
  { fr: "Un bandana rouge noué à leur cuisse, un souvenir d'un gang qu'ils ont quitté", en: "A red bandana tied to their thigh, a memento from a gang they left" },
  { fr: "Une cravate en soie Vashon Island portée comme bandeau de tête lors des combats", en: "A Vashon Island silk tie worn as a headband during fights" },
  { fr: "Une paire de Doc Martens recollées au moins vingt fois, irremplaçables", en: "A pair of Doc Martens reglued at least twenty times, irreplaceable" },
  { fr: "Un gant unique en kevlar souple, l'autre perdu lors d'une extraction ratée", en: "A single soft kevlar glove, the other lost during a botched extraction" },
  { fr: "Un pin's émaillé du logo de la UCAS épinglé à l'envers sur leur veste", en: "An enameled UCAS logo pin fastened upside down on their jacket" },
  { fr: "Une boucle de ceinture en forme de tête de loup, héritée de trois propriétaires morts", en: "A wolf-head belt buckle, inherited from three dead previous owners" },
  { fr: "Un foulard en soie taché de sang qu'ils n'ont jamais lavé et ne laveront jamais", en: "A silk handkerchief stained with blood they've never washed and never will" },

  // ——— More sentimental items ———
  { fr: "Un harmonica cabossé qui ne joue plus que trois notes, un cadeau de leur père", en: "A dented harmonica that only plays three notes, a gift from their father" },
  { fr: "La plaque d'identité militaire de leur jumeau mort à Bug City", en: "The military ID tag of their twin who died at Bug City" },
  { fr: "Un hologramme figé montrant un enfant riant — leur fils qu'ils n'ont jamais revu", en: "A frozen hologram showing a laughing child — their son they never saw again" },
  { fr: "Une bague de fiançailles dont le diamant a été remplacé par un éclat de balle", en: "An engagement ring whose diamond has been replaced with a bullet fragment" },
  { fr: "Un vieux pass de concert pour un groupe qui n'existe plus depuis le Crash", en: "An old concert pass for a band that hasn't existed since the Crash" },
  { fr: "Le dernier message vocal de leur coéquipier, stocké sur une puce isolée du réseau", en: "Their teammate's last voicemail, stored on a chip isolated from the network" },
  { fr: "Un marque-page en cuir pressé entre les pages d'un livre qu'ils ne possèdent plus", en: "A leather bookmark pressed between the pages of a book they no longer own" },

  // ——— More lucky charms ———
  { fr: "Un fer à cheval miniature en acier forgé par un nain de Seattle", en: "A miniature horseshoe forged from steel by a Seattle dwarf" },
  { fr: "Un boulon rouillé trouvé sur le toit d'où ils ont échappé à une embuscade", en: "A rusty bolt found on the rooftop where they escaped an ambush" },
  { fr: "Une carte de tarot — Le Pendu — trouvée dans la main d'un mort qui leur souriait", en: "A tarot card — The Hanged Man — found in the hand of a smiling corpse" },
  { fr: "Un morceau de kevlar découpé dans le gilet qui leur a sauvé la vie", en: "A piece of kevlar cut from the vest that saved their life" },
  { fr: "Un galet parfaitement rond ramassé sur une plage la veille de leur première mort clinique", en: "A perfectly round pebble picked up from a beach the day before their first clinical death" },

  // ——— More trophies ———
  { fr: "La montre à gousset d'un yakuza oyabun qu'ils ont battu au combat singulier", en: "The pocket watch of a Yakuza oyabun they defeated in single combat" },
  { fr: "Un fragment de masque de cérémonie arraché à un adepte du Loup de Fenris", en: "A fragment of a ceremonial mask torn from a Fenris Wolf adept" },
  { fr: "Un bout de câble porteur du pont dont ils ont fait tomber un hélicoptère corpo", en: "A piece of support cable from the bridge where they brought down a corpo helicopter" },
  { fr: "La fibule en argent d'un prince elfique du Tir na nÓg qu'ils ont humilié", en: "The silver brooch of a Tir na nÓg elven prince they humiliated" },
  { fr: "Le numéro de série gravé d'un tank Ares qu'ils ont neutralisé avec une bombe artisanale", en: "The engraved serial number plate of an Ares tank they disabled with a homemade bomb" },

  // ——— More weird collections ———
  { fr: "Un fil électrique sur lequel sont enfilés des SIN falsifiés périmés, comme un collier de perles", en: "An electric wire strung with expired fake SINs, like a pearl necklace" },
  { fr: "Trente-sept capsules de bouteilles, une pour chaque bar où ils ont été virés", en: "Thirty-seven bottle caps, one for each bar they've been thrown out of" },
  { fr: "Un bocal d'yeux de verre de différentes couleurs achetés dans des marchés noirs", en: "A jar of glass eyes of different colors bought at black markets" },
  { fr: "Un étui rempli de puces mémoire vierges qu'ils distribuent comme des cartes de visite", en: "A case full of blank memory chips they hand out like business cards" },
  { fr: "Un rouleau de papier toilette vintage d'avant le Crash, gardé comme trésor inestimable", en: "A roll of vintage pre-Crash toilet paper, kept as a priceless treasure" },

  // ——— More old world relics ———
  { fr: "Un Game Boy fonctionnel avec une cartouche de Tetris dont le score maximal n'a jamais été battu", en: "A working Game Boy with a Tetris cartridge whose high score has never been beaten" },
  { fr: "Un Polaroid Instax avec trois photos restantes qu'ils refusent d'utiliser à la légère", en: "A Polaroid Instax with three remaining shots they refuse to waste" },
  { fr: "Un journal intime papier rempli à moitié, écrit dans un code qu'ils ont eux-mêmes oublié", en: "A half-filled paper diary written in a code they themselves have forgotten" },
  { fr: "Un plan de métro papier de Seattle datant de 2045, annoté de symboles mystérieux", en: "A paper Seattle metro map from 2045, annotated with mysterious symbols" },
  { fr: "Un exemplaire papier du Manifeste Néo-Anarchiste, corné et souligné à chaque page", en: "A paper copy of the Neo-Anarchist Manifesto, dog-eared and underlined on every page" },

  // ——— More tech items ———
  { fr: "Un bras cybernétique miniature articulé, prototype d'un ami ingénieur assassiné", en: "A miniature articulated cybernetic arm, a prototype from a murdered engineer friend" },
  { fr: "Un patch neural grillé qui leur a donné des migraines pendant un an", en: "A burned-out neural patch that gave them migraines for a year" },
  { fr: "Un bout de câble de fibre optique tressé en forme de nœud celtique", en: "A length of fiber optic cable braided into a Celtic knot" },
  { fr: "Une lentille de contact AR périmée qu'ils gardent dans un petit étui en titane", en: "An expired AR contact lens they keep in a small titanium case" },
  { fr: "Le dernier message d'un agent de la Matrice qu'ils ont laissé mourir, affiché sur un écran miniature", en: "The last message of a Matrix agent they let die, displayed on a miniature screen" },

  // ——— More magical objects ———
  { fr: "Un bâton d'encens qui ne finit jamais de brûler et dégage une odeur de forêt primitive", en: "A stick of incense that never finishes burning and smells like primordial forest" },
  { fr: "Un coquillage spiral qui murmure des mots dans une langue morte quand on le porte à l'oreille", en: "A spiral shell that whispers words in a dead language when held to the ear" },
  { fr: "Un tatouage vivant sur leur avant-bras qui bouge lentement au fil des jours", en: "A living tattoo on their forearm that moves slowly over the course of days" },
  { fr: "Un éclat de météorite trouvé dans un cercle de cultures du Pays de Galles", en: "A meteorite fragment found in a crop circle in Wales" },
  { fr: "Une petite fiole de larmes de phénix cristallisées qu'on leur a vendues comme authentiques", en: "A small vial of crystallized phoenix tears sold to them as authentic" },

  // ——— More food/drink ———
  { fr: "Un sachet de pop-corn micro-ondes pré-Éveil, gonflé et jamais ouvert", en: "A bag of pre-Awakening microwave popcorn, puffed up and never opened" },
  { fr: "Un flacon de vanille véritable gardé pour parfumer le soja quand le moral est au plus bas", en: "A vial of real vanilla kept to flavor soy when morale is at its lowest" },
  { fr: "Une tablette de chewing-gum dont ils mâchent un morceau par an, rituel strict", en: "A pack of chewing gum from which they chew one piece per year, strict ritual" },
  { fr: "Un tube de wasabi authentique, trésor inestimable dans un monde de synthétique", en: "A tube of authentic wasabi, a priceless treasure in a world of synthetics" },
  { fr: "Une bouteille de sake miniature offerte par un yakuza en signe de respect mutuel", en: "A miniature bottle of sake given by a Yakuza as a sign of mutual respect" },

  // ——— More clothing/accessories ———
  { fr: "Un lacet de botte noué sept fois, un pour chaque promesse qu'ils ont tenue", en: "A boot lace tied in seven knots, one for each promise they've kept" },
  { fr: "Un bandeau oculaire en cuir qu'ils portent parfois sans raison médicale apparente", en: "A leather eye patch they sometimes wear for no apparent medical reason" },
  { fr: "Des boutons de manchette fabriqués à partir de douilles de balles, hérités de leur mentor", en: "Cufflinks made from bullet casings, inherited from their mentor" },
  { fr: "Une veste en cuir avec un trou de balle dans le dos, jamais réparé par superstition", en: "A leather jacket with a bullet hole in the back, never repaired out of superstition" },
  { fr: "Une chevalière gravée d'un blason familial d'une famille noble qui n'existe plus", en: "A signet ring engraved with the coat of arms of a noble family that no longer exists" },

  // ——— Mixed / unique ———
  { fr: "Un cube de Rubik dont les faces ont été repeintes aux couleurs des six mégacorpos", en: "A Rubik's Cube with faces repainted in the colors of the six megacorporations" },
  { fr: "Un bout de craie qui dessine toujours en bleu, quelle que soit la surface", en: "A piece of chalk that always draws in blue, regardless of the surface" },
  { fr: "Une figurine de dragon en étain, le pouce usé à force de la caresser nerveusement", en: "A pewter dragon figurine, its thumb-spot worn smooth from nervous fidgeting" },
  { fr: "Un canif suisse avec tous les outils cassés sauf le tire-bouchon", en: "A Swiss Army knife with every tool broken except the corkscrew" },
  { fr: "Un jeu de runes gravées sur des morceaux de circuit imprimé récupérés", en: "A set of runes carved on salvaged circuit board fragments" },
  { fr: "Un petit pot de peinture noire avec lequel ils repeignent leur masque avant chaque run", en: "A small pot of black paint they use to repaint their mask before every run" },
  { fr: "Un sifflet ultrasonique qui ne produit aucun son audible par les humains", en: "An ultrasonic whistle that produces no sound audible to humans" },
  { fr: "Une bague d'humeur cybernétique qui affiche leur rythme cardiaque en temps réel", en: "A cybernetic mood ring that displays their heart rate in real time" },
  { fr: "Un ticket de cinéma pour un film qui n'est jamais sorti en salles", en: "A movie ticket for a film that was never released in theaters" },
  { fr: "Un crayon à papier HB qu'ils taillent rituellement mais n'utilisent jamais pour écrire", en: "An HB pencil they ritually sharpen but never use to write" },
  { fr: "Un morceau de béton peint en or provenant du mur de Berlin, authentique selon eux", en: "A piece of concrete painted gold from the Berlin Wall, authentic according to them" },
  { fr: "Un jeton de métro de Neo-Tokyo qui ne correspond à aucune ligne connue", en: "A Neo-Tokyo metro token that doesn't match any known line" },
  { fr: "Une boussole dont l'aiguille pointe toujours vers le sud-ouest sans raison explicable", en: "A compass whose needle always points southwest for no explainable reason" },
  { fr: "Un briquet qui ne s'allume qu'une fois sur dix, mais jamais quand on n'en a pas besoin", en: "A lighter that only ignites one time in ten, but never when it's not needed" },
  { fr: "Un flocon de neige artificiel conservé dans une bulle de résine depuis leur enfance", en: "An artificial snowflake preserved in a resin bubble since their childhood" },
  { fr: "Un fil rouge noué à leur petit doigt, l'autre extrémité coupée net", en: "A red thread tied to their little finger, the other end cut clean" },
  { fr: "Un morceau d'ambre contenant un moustique, trouvé ironiquement dans un cinéma abandonné", en: "A piece of amber containing a mosquito, found ironically in an abandoned movie theater" },
  { fr: "Une plaque de métal gravée 'PROPRIÉTÉ DE LONE STAR — NE PAS VOLER' qu'ils ont volée", en: "A metal plate engraved 'LONE STAR PROPERTY — DO NOT STEAL' which they stole" },
  { fr: "Un pendule en cristal noir qui oscille tout seul quand personne ne regarde", en: "A black crystal pendulum that swings on its own when nobody's looking" },
  { fr: "Un minuscule carnet de coupons de réduction tous expirés, feuilleté comme un doudou", en: "A tiny coupon booklet, all expired, thumbed through like a comfort blanket" },
  { fr: "Un cure-dent en métal gravé de nanoglyphes illisibles, trouvé dans la poche d'un cadavre", en: "A metal toothpick engraved with unreadable nanoglyphs, found in a corpse's pocket" },
  { fr: "Un morceau de verre de mer bleu cobalt ramassé sur les rives toxiques du Puget Sound", en: "A cobalt blue sea glass shard picked up from the toxic shores of Puget Sound" },
  { fr: "Un bouchon de liège d'une bouteille de champagne ouverte le soir où tout a mal tourné", en: "A cork from a champagne bottle opened the night everything went wrong" },
  { fr: "Un petit robot jouet à remontoir qui marche en cercle et tombe du bord des tables", en: "A small wind-up toy robot that walks in circles and falls off table edges" },
  { fr: "Une longue-vue en laiton miniature qui ne grossit rien mais à laquelle ils tiennent", en: "A miniature brass spyglass that magnifies nothing but they cherish" },
  { fr: "Un pion de jeu d'échecs — le roi noir — taillé dans du bois véritable", en: "A chess piece — the black king — carved from real wood" },

  // ——— Additional sentimental items ———
  { fr: "Une broche en argent ternie offerte par une elfe qu'ils ont aimée en secret", en: "A tarnished silver brooch given by an elf they secretly loved" },
  { fr: "Un ruban de satin violet noué autour de leur poignet depuis le jour où leur sœur est partie", en: "A purple satin ribbon tied around their wrist since the day their sister left" },
  { fr: "Un caillou peint par leur fille adoptive, représentant un soleil jaune sur fond bleu", en: "A pebble painted by their adopted daughter, showing a yellow sun on a blue background" },
  { fr: "Un morceau de papier froissé avec un numéro de commlink qui ne répond plus depuis cinq ans", en: "A crumpled piece of paper with a commlink number that hasn't answered in five years" },
  { fr: "La pointe d'une flèche retirée de leur épaule, gardée dans un petit sac en daim", en: "An arrowhead removed from their shoulder, kept in a small suede pouch" },
  { fr: "Un demi-pendentif en forme de cœur dont l'autre moitié repose dans une tombe anonyme", en: "Half a heart-shaped pendant whose other half rests in an unmarked grave" },
  { fr: "Un vieux gant de boxe miniature accroché à leur ceinture, souvenir de leur père entraîneur", en: "A tiny boxing glove keychain clipped to their belt, a memento of their trainer father" },
  { fr: "Un morceau de papier plié contenant la recette du ragoût de leur grand-mère ork", en: "A folded piece of paper containing their ork grandmother's stew recipe" },
  { fr: "Un bouton de nacre arraché à la robe de leur mère le jour des funérailles", en: "A mother-of-pearl button torn from their mother's dress the day of the funeral" },
  { fr: "Une mèche de cheveux bleus tressée avec soin, appartenant à leur premier amour", en: "A carefully braided lock of blue hair belonging to their first love" },
  { fr: "Un enregistrement holographique de trente secondes montrant leur village natal avant sa destruction", en: "A thirty-second holographic recording showing their hometown before its destruction" },
  { fr: "Un petit cadre photo numérique cassé, figé sur l'image d'un groupe d'amis disparus", en: "A small broken digital photo frame, frozen on an image of a group of vanished friends" },
  { fr: "Une chaîne de cheville offerte par un chamane qui les a guéris d'une maladie mortelle", en: "An ankle chain given by a shaman who healed them of a deadly illness" },
  { fr: "Le premier nuyen qu'ils ont gagné honnêtement, percé et porté en collier", en: "The first nuyen they earned honestly, pierced and worn as a necklace" },
  { fr: "Un briquet cabossé portant l'inscription 'Pour toujours', offert par quelqu'un dont ils ont oublié le nom", en: "A dented lighter inscribed 'Forever', given by someone whose name they've forgotten" },
  { fr: "Un morceau de tissu à carreaux découpé dans la chemise de leur mentor assassiné", en: "A plaid fabric swatch cut from their murdered mentor's shirt" },
  { fr: "Une fausse fleur en plastique jaunie qu'ils déposaient chaque semaine sur une tombe", en: "A yellowed plastic flower they used to place on a grave every week" },
  { fr: "Un billet d'avion papier pour un vol qui n'a jamais décollé", en: "A paper plane ticket for a flight that never took off" },
  { fr: "Un petit coquillage ramassé avec leur frère sur la dernière plage propre de Californie", en: "A small seashell collected with their brother on the last clean beach in California" },
  { fr: "Une dent de lait conservée dans un minuscule flacon, celle de leur enfant jamais retrouvé", en: "A baby tooth kept in a tiny vial, from their child who was never found" },

  // ——— Additional lucky charms ———
  { fr: "Un œil de chat en verre qu'ils serrent dans leur poing avant de tirer", en: "A glass cat's eye marble they squeeze in their fist before shooting" },
  { fr: "Un petit sac de poudre dorée qu'ils lancent en l'air quand la situation devient critique", en: "A small bag of gold powder they toss in the air when things get critical" },
  { fr: "Un vieux kopeck russe percé trouvé dans les décombres de Vladivostok", en: "An old pierced Russian kopeck found in the rubble of Vladivostok" },
  { fr: "Un pendentif en forme de fer à cheval inversé qu'ils prétendent plus efficace ainsi", en: "An upside-down horseshoe pendant they claim works better that way" },
  { fr: "Un noyau de cerise séché qu'ils font tourner entre leurs doigts lors des négociations", en: "A dried cherry pit they roll between their fingers during negotiations" },
  { fr: "Un petit scarabée en cuivre acheté à un marchand aveugle du Caire", en: "A small copper scarab bought from a blind merchant in Cairo" },
  { fr: "Un morceau de corde de pendu qu'un vieux troll leur a vendu comme porte-bonheur", en: "A piece of hangman's rope an old troll sold them as a good luck charm" },
  { fr: "Un coquillage nacré trouvé dans l'estomac d'un poisson Éveillé", en: "A pearlescent shell found in the stomach of an Awakened fish" },
  { fr: "Un bouton de porte en porcelaine rescapé de l'explosion qui a détruit leur premier appartement", en: "A porcelain doorknob salvaged from the explosion that destroyed their first apartment" },
  { fr: "Un galet gravé du mot 'chance' en mandarin par un adepte qui a survécu à l'impossible", en: "A pebble engraved with the word 'luck' in Mandarin by an adept who survived the impossible" },
  { fr: "Un fragment de pneu de la moto qui les a sauvés de leur première embuscade corpo", en: "A tire fragment from the motorcycle that saved them from their first corpo ambush" },
  { fr: "Un petit cube métallique magnétique qui s'oriente toujours vers le nord quand posé", en: "A small magnetic metal cube that always orients north when set down" },
  { fr: "Un jeton de casino de Macao qu'ils n'ont jamais encaissé", en: "A Macau casino chip they never cashed in" },
  { fr: "Un pendentif en dent de requin offert par un pirate du Pacifique", en: "A shark tooth pendant given by a Pacific pirate" },
  { fr: "Un trèfle en métal forgé par un nain artisan qui jurait qu'il était enchanté", en: "A metal clover forged by a dwarf craftsman who swore it was enchanted" },

  // ——— Additional trophies ———
  { fr: "Un bouton d'uniforme d'un garde Red Samurai qu'ils ont assommé sans être repéré", en: "A uniform button from a Red Samurai guard they knocked out undetected" },
  { fr: "Un éclat de pare-brise blindé provenant de la limousine d'un prince corporatiste", en: "A shard of armored windshield from a corporate prince's limousine" },
  { fr: "Le communicateur personnel d'un officier de Knight Errant, gravé de son nom", en: "The personal communicator of a Knight Errant officer, engraved with their name" },
  { fr: "Un morceau de tentacule séché d'un esprit de l'eau qu'ils ont combattu sous la pluie", en: "A dried tentacle piece from a water spirit they fought in the rain" },
  { fr: "La visière brisée d'un casque de CRS Lone Star, fendue en deux d'un seul coup", en: "The cracked visor of a Lone Star riot helmet, split in two with one blow" },
  { fr: "Un insigne de pilote de T-bird arraché dans un cockpit en plein vol", en: "A T-bird pilot's insignia ripped from a cockpit mid-flight" },
  { fr: "Un morceau d'écaille prélevé sur un drake qu'ils prétendent avoir terrassé seul", en: "A scale fragment taken from a drake they claim to have slain alone" },
  { fr: "La carte d'identité corpo d'un chercheur Shiawase qu'ils ont libéré de force", en: "The corporate ID of a Shiawase researcher they forcibly liberated" },
  { fr: "Un fragment de crâne cybernétique d'un rival qu'ils ont vaincu en combat de rue", en: "A fragment of cybernetic skull from a rival they defeated in a street fight" },
  { fr: "Un bout de tissu arraché au drapeau d'une nation tribale qu'ils ont défendue", en: "A torn piece of cloth from a tribal nation's flag they defended" },
  { fr: "Un pic à glace tordu ayant servi à crocheter la serrure d'un coffre-fort Zurich Orbital", en: "A bent ice pick used to pick the lock of a Zurich Orbital vault" },
  { fr: "La boucle d'oreille d'un assassin Léopard qu'ils ont retourné contre ses employeurs", en: "The earring of a Leopard assassin they turned against their employers" },
  { fr: "Un morceau de blindage réactif arraché à un tank Aztechnology lors du siège de Bogota", en: "A piece of reactive armor torn from an Aztechnology tank during the siege of Bogota" },

  // ——— Additional weird collections ———
  { fr: "Un sac de billes de pachinko récupérées dans des salles de jeux de Neo-Tokyo", en: "A bag of pachinko balls collected from Neo-Tokyo game parlors" },
  { fr: "Une collection de tickets de transport de douze villes différentes, classés par date", en: "A collection of transit tickets from twelve different cities, sorted by date" },
  { fr: "Un étui contenant des éclats de verre coloré ramassés après chaque fusillade", en: "A case containing colored glass shards collected after every shootout" },
  { fr: "Vingt-trois bouchons de stylo dépareillés gardés dans une boîte d'allumettes", en: "Twenty-three mismatched pen caps kept in a matchbox" },
  { fr: "Un carnet spirale rempli de numéros de commlink de gens qu'ils n'ont jamais rappelés", en: "A spiral notebook full of commlink numbers of people they never called back" },
  { fr: "Un sac de jetons de jeux d'arcade vintage dont aucune machine n'existe plus", en: "A bag of vintage arcade tokens for machines that no longer exist" },
  { fr: "Quarante et un échantillons de terre de chaque pays où ils ont travaillé", en: "Forty-one soil samples from every country where they've worked" },
  { fr: "Une guirlande de capsules de soykaf enfilées sur un fil de cuivre", en: "A garland of soykaf capsules strung on copper wire" },
  { fr: "Un porte-cartes rempli de fausses identités périmées qu'ils gardent par nostalgie", en: "A card holder full of expired fake IDs they keep out of nostalgia" },
  { fr: "Un sac en plastique contenant des fragments de chaque arme qu'ils ont cassée", en: "A plastic bag containing fragments of every weapon they've broken" },
  { fr: "Un album de timbres-poste d'avant le Crash, soigneusement entretenu", en: "A stamp album from before the Crash, carefully maintained" },
  { fr: "Un bocal contenant des boulons et écrous récupérés sur des drones abattus", en: "A jar of bolts and nuts salvaged from downed drones" },

  // ——— Additional old world relics ———
  { fr: "Un iPod Classic avec une playlist de 2024 qu'ils connaissent par cœur", en: "An iPod Classic with a 2024 playlist they know by heart" },
  { fr: "Un agenda en cuir de 2028 avec des rendez-vous que personne n'a honorés", en: "A leather planner from 2028 with appointments no one kept" },
  { fr: "Un stylo à bille publicitaire d'une entreprise qui n'a pas survécu au Crash 2.0", en: "An advertising ballpoint pen from a company that didn't survive Crash 2.0" },
  { fr: "Un magazine papier de mode de 2031, les mannequins semblent appartenir à un autre monde", en: "A paper fashion magazine from 2031, the models seem to belong to another world" },
  { fr: "Une calculatrice solaire des années 2010 qui fonctionne encore parfaitement", en: "A solar-powered calculator from the 2010s that still works perfectly" },
  { fr: "Un réveil mécanique à clochettes qui sonne encore à 6h chaque matin", en: "A mechanical bell alarm clock that still rings at 6 AM every morning" },
  { fr: "Un baladeur CD avec un seul disque rayé qu'ils écoutent quand même", en: "A portable CD player with one scratched disc they listen to anyway" },
  { fr: "Un guide touristique papier de Paris datant de 2025, rempli de notes dans les marges", en: "A paper Paris travel guide from 2025, filled with margin notes" },
  { fr: "Un vieux clavier mécanique de PC dont ils ne gardent que la touche Escape en pendentif", en: "An old mechanical PC keyboard from which they only keep the Escape key as a pendant" },
  { fr: "Une carte routière pliée de l'autoroute I-5, annotée avec des routes de contrebande", en: "A folded I-5 highway road map annotated with smuggling routes" },
  { fr: "Un flacon de parfum presque vide d'une marque disparue, qu'ils sentent rarement", en: "A nearly empty perfume bottle from a vanished brand, rarely sniffed" },
  { fr: "Un taille-crayon en métal en forme de globe terrestre, hérité de leur instituteur", en: "A metal pencil sharpener shaped like a globe, inherited from their schoolteacher" },

  // ——— Additional tech items ———
  { fr: "Un nanodrone grillé pas plus gros qu'un moustique, épinglé sur leur col", en: "A fried nanodrone no bigger than a mosquito, pinned to their collar" },
  { fr: "Un câble rétractable de datajack modifié pour servir de garrot en urgence", en: "A retractable datajack cable modified to serve as an emergency tourniquet" },
  { fr: "Un processeur quantique miniature encapsulé dans du cristal, purement décoratif", en: "A miniature quantum processor encased in crystal, purely decorative" },
  { fr: "Un clavier holographique portable qui ne projette plus que la lettre Q en boucle", en: "A portable holographic keyboard that now only projects the letter Q on loop" },
  { fr: "Un bracelet fait de fils de fibre optique récupérés sur un serveur Renraku démantelé", en: "A bracelet made from fiber optic wires salvaged from a dismantled Renraku server" },
  { fr: "Un ancien récepteur radio analogique miniature captant une fréquence fantôme inconnue", en: "An old miniature analog radio receiver picking up an unknown ghost frequency" },
  { fr: "Un disque optique gravé contenant les plans d'un prototype jamais construit", en: "An etched optical disc containing blueprints for a prototype never built" },
  { fr: "Un petit panneau solaire flexible qu'ils utilisent pour recharger un appareil que personne n'a jamais vu", en: "A small flexible solar panel they use to charge a device no one has ever seen" },
  { fr: "Un oculaire de smartgun grillé transformé en monocle décoratif", en: "A burnt-out smartgun eyepiece turned into a decorative monocle" },
  { fr: "Un fragment de nœud matriciel solidifié, vestige d'un crash de la Matrice locale", en: "A solidified Matrix node fragment, a remnant of a local Matrix crash" },
  { fr: "Un petit écran e-ink affichant en permanence un compte à rebours dont personne ne connaît l'échéance", en: "A small e-ink screen permanently displaying a countdown whose deadline no one knows" },
  { fr: "Un microphone cybernétique sous-cutané retiré de leur gorge, monté en bague", en: "A subcutaneous cybernetic microphone removed from their throat, mounted as a ring" },
  { fr: "Un concentrateur WiFi artisanal gros comme un pouce qui capte des signaux depuis les ruines", en: "A thumb-sized homemade WiFi concentrator that picks up signals from the ruins" },
  { fr: "Un circuit imprimé flexible enroulé en bracelet, couvert de soudures faites à la main", en: "A flexible circuit board rolled into a bracelet, covered in hand-soldered joints" },

  // ——— Additional magical objects ———
  { fr: "Un éclat de cristal d'orichalque trop petit pour être utile mais trop précieux pour être vendu", en: "An orichalcum crystal shard too small to be useful but too precious to sell" },
  { fr: "Un petit totem en bois sculpté représentant un corbeau aux yeux de rubis", en: "A small carved wooden totem depicting a raven with ruby eyes" },
  { fr: "Une fiole de sang de licorne séché que personne n'a pu authentifier", en: "A vial of dried unicorn blood that no one has been able to authenticate" },
  { fr: "Un anneau en fer froid qui gèle au contact des esprits", en: "A cold iron ring that freezes upon contact with spirits" },
  { fr: "Un parchemin miniature couvert de sigils protecteurs tracés à l'encre phosphorescente", en: "A miniature scroll covered in protective sigils drawn in phosphorescent ink" },
  { fr: "Un sachet de cendres provenant d'un cercle d'invocation raté qu'ils portent comme avertissement", en: "A pouch of ashes from a failed summoning circle they wear as a warning" },
  { fr: "Une fleur séchée d'un jardin astral qui ne fane jamais complètement", en: "A dried flower from an astral garden that never fully wilts" },
  { fr: "Un galet trouvé au centre exact d'un lieu de pouvoir, tiède en permanence", en: "A pebble found at the exact center of a power site, perpetually warm" },
  { fr: "Un petit flacon contenant de la brume capturée lors d'une tempête de mana", en: "A small vial containing mist captured during a mana storm" },
  { fr: "Une dent de serpent à plumes enchantée qui siffle doucement quand la lune est pleine", en: "An enchanted feathered serpent tooth that whistles softly when the moon is full" },
  { fr: "Un pendentif contenant une goutte d'eau d'un lac sacré du Tir Tairngire, figée en cristal", en: "A pendant containing a drop of water from a sacred Tir Tairngire lake, frozen in crystal" },
  { fr: "Un petit miroir de divination dont le reflet montre toujours le lever du soleil", en: "A small divination mirror whose reflection always shows sunrise" },
  { fr: "Une racine de mandragore séchée qui grince parfois quand on la déplace", en: "A dried mandrake root that occasionally creaks when moved" },
  { fr: "Un éclat d'ambre contenant une fourmi Éveillée qui semble se déplacer au ralenti", en: "An amber shard containing an Awakened ant that seems to move in slow motion" },

  // ——— Additional food/drink ———
  { fr: "Un petit flacon d'huile de truffe véritable gardé pour des occasions qui n'arrivent jamais", en: "A small vial of real truffle oil saved for occasions that never come" },
  { fr: "Un paquet de ramen instantané d'avant le Crash, conservé sous vide par précaution", en: "A packet of instant ramen from before the Crash, vacuum-sealed as a precaution" },
  { fr: "Une fiole de vrai sirop d'érable que même un dragon ne pourrait leur acheter", en: "A vial of real maple syrup that not even a dragon could buy from them" },
  { fr: "Un sachet de graines de café torréfiées à la main par un fermier troll de Colombie", en: "A pouch of coffee beans hand-roasted by a troll farmer in Colombia" },
  { fr: "Une boîte de sardines millésimée qu'ils considèrent comme un investissement financier", en: "A vintage tin of sardines they consider a financial investment" },
  { fr: "Un petit pot de confiture de framboise fait maison, le dernier avant l'effondrement de la ferme", en: "A small jar of homemade raspberry jam, the last before the farm collapsed" },
  { fr: "Un cube de sucre véritable enveloppé dans du papier doré comme un bijou", en: "A real sugar cube wrapped in gold paper like a jewel" },
  { fr: "Une tablette de chocolat noir 90% d'avant le Crash, soigneusement divisée en carrés rationnés", en: "A 90% dark chocolate bar from before the Crash, carefully divided into rationed squares" },
  { fr: "Une pomme synthétique dorée qu'ils gardent pour rappeler que tout est faux dans ce monde", en: "A golden synthetic apple they keep as a reminder that everything is fake in this world" },
  { fr: "Un sachet de sel rose de l'Himalaya, plus cher que la plupart des drogues de rue", en: "A pouch of Himalayan pink salt, more expensive than most street drugs" },

  // ——— Additional clothing/accessories ———
  { fr: "Un masque de bal vénitien fendu en deux qu'ils portent lors des infiltrations", en: "A Venetian masquerade mask split in two that they wear during infiltrations" },
  { fr: "Un gant de cuir noir avec des runes cousues à l'intérieur, hérité d'un adepte physique", en: "A black leather glove with runes sewn inside, inherited from a physical adept" },
  { fr: "Une épaulette militaire UCAS cousue sur leur veste civile, provocation assumée", en: "A UCAS military epaulette sewn onto their civilian jacket, deliberate provocation" },
  { fr: "Un foulard en soie imprimé d'un plan de la Matrice de Seattle circa 2060", en: "A silk scarf printed with a map of the Seattle Matrix circa 2060" },
  { fr: "Des lunettes de soudeur modifiées avec des verres teintés en violet permanent", en: "Modified welder's goggles with permanently purple-tinted lenses" },
  { fr: "Une paire de bretelles en cuir synthétique ornées de minuscules crânes en métal", en: "A pair of synthetic leather suspenders adorned with tiny metal skulls" },
  { fr: "Un chapeau melon écrasé qu'ils remettent en forme avant chaque rencontre avec un Johnson", en: "A crushed bowler hat they reshape before every meeting with a Johnson" },
  { fr: "Un bracelet de force en kevlar tressé portant la devise 'Mors Ultima Ratio'", en: "A braided kevlar wristband bearing the motto 'Mors Ultima Ratio'" },
  { fr: "Une ceinture faite de maillons de chaîne récupérés dans un camp de prisonniers", en: "A belt made from chain links recovered from a prison camp" },
  { fr: "Un col roulé blindé noir qu'ils portent même en pleine canicule", en: "A black armored turtleneck they wear even in scorching heat" },

  // ——— Additional mixed/unique ———
  { fr: "Un morceau de charbon compressé qu'ils prétendent deviendra un diamant dans mille ans", en: "A piece of compressed coal they claim will become a diamond in a thousand years" },
  { fr: "Un flacon d'air mis en bouteille dans les montagnes du Tir na nÓg", en: "A bottle of air collected in the mountains of Tir na nÓg" },
  { fr: "Un cadenas sans clé qu'ils ouvrent et ferment nerveusement d'un tour de pouce", en: "A keyless padlock they nervously open and close with a thumb turn" },
  { fr: "Une fléchette de bar plantée dans un bouchon de liège, souvenir d'un pari gagné contre un troll", en: "A bar dart stuck in a cork, a memento of a bet won against a troll" },
  { fr: "Un petit sablier de cuisine dont le sable est remplacé par de la poudre de dragon", en: "A small kitchen timer hourglass whose sand is replaced with dragon powder" },
  { fr: "Un chronomètre mécanique arrêté sur 00:07:13, leur record personnel de fuite", en: "A mechanical stopwatch stopped at 00:07:13, their personal escape record" },
  { fr: "Un petit globe à neige contenant une réplique miniature du centre-ville de Seattle", en: "A small snow globe containing a miniature replica of downtown Seattle" },
  { fr: "Un harmonica chromé qu'ils savent jouer mais refusent d'utiliser devant quiconque", en: "A chrome harmonica they know how to play but refuse to use in front of anyone" },
  { fr: "Un vieux passe-partout qui n'ouvre plus rien mais qu'ils essayent sur chaque serrure", en: "An old master key that opens nothing anymore but they try on every lock" },
  { fr: "Un mètre ruban en tissu que leur mère couturière utilisait, marqué en pouces et en centimètres", en: "A cloth tape measure their seamstress mother used, marked in inches and centimeters" },
  { fr: "Un kaléidoscope miniature fabriqué à partir de douilles de balles et d'éclats de verre coloré", en: "A miniature kaleidoscope made from bullet casings and colored glass shards" },
  { fr: "Un petit flacon de sable noir volcanique d'Hawaï, scellé à la cire", en: "A small vial of black volcanic sand from Hawaii, wax-sealed" },
  { fr: "Un fragment de miroir sans tain récupéré dans une salle d'interrogatoire de Lone Star", en: "A one-way mirror fragment salvaged from a Lone Star interrogation room" },
  { fr: "Un porte-bonheur en forme de maneki-neko dont la patte bouge encore grâce à une pile éternelle", en: "A maneki-neko lucky cat charm whose paw still waves thanks to an everlasting battery" },
  { fr: "Un dé à vingt faces en obsidienne utilisé pour prendre chaque décision importante", en: "A twenty-sided obsidian die used to make every important decision" },
  { fr: "Un petit carillon éolien fait de clés anciennes qui tintent à chaque mouvement", en: "A small wind chime made of old keys that jingle with every movement" },
  { fr: "Un billet de banque pré-nuyen encadré dans une plaque de plastique transparente", en: "A pre-nuyen banknote encased in a clear plastic slab" },
  { fr: "Un petit automate mécanique en laiton représentant un oiseau qui bat des ailes quand on le remonte", en: "A small brass mechanical automaton of a bird that flaps its wings when wound up" },
  { fr: "Un écusson de pompier de Seattle trouvé dans les décombres d'une caserne abandonnée", en: "A Seattle firefighter's badge found in the rubble of an abandoned station" },
  { fr: "Un morceau de rail magnétique arraché au monorail de Seattle", en: "A piece of magnetic rail torn from the Seattle monorail" },
  { fr: "Un petit tambour chamanique miniature qu'ils tapotent du bout des doigts quand ils s'ennuient", en: "A miniature shamanic drum they tap with their fingertips when bored" },
  { fr: "Un fragment de vitrail volé dans une église abandonnée des Barrens", en: "A stained glass fragment stolen from an abandoned church in the Barrens" },
  { fr: "Un monocle en verre fumé qu'ils prétendent améliorer leur perception astrale", en: "A smoked glass monocle they claim enhances their astral perception" },
  { fr: "Un minuscule livre de prières en latin relié en cuir, usé jusqu'à la corde", en: "A tiny leather-bound Latin prayer book, worn to a thread" },
  { fr: "Un petit cactus cybernétique en pot qui n'a besoin ni d'eau ni de lumière", en: "A small potted cybernetic cactus that needs neither water nor light" },
  { fr: "Un sextant miniature en cuivre qui ne pointe vers aucune étoile connue", en: "A miniature copper sextant that doesn't point to any known star" },
  { fr: "Un jeton métallique frappé de l'inscription 'Membre à vie' d'un club qui a brûlé", en: "A metal token stamped 'Lifetime Member' from a club that burned down" },
  { fr: "Un minuscule aquarium scellé contenant une crevette bioluminescente Éveillée", en: "A tiny sealed aquarium containing a bioluminescent Awakened shrimp" },
  { fr: "Un vieux transistor radio qui ne capte qu'une station diffusant du jazz en continu", en: "An old transistor radio that only picks up one station playing continuous jazz" },
  { fr: "Un peigne en corne véritable dont les dents sont limées en pointe", en: "A genuine horn comb with teeth filed to a point" },

  // ——— Shadowrun-specific lore items ———
  { fr: "Un fragment de barricade du soulèvement ork de la Nuit de la Rage", en: "A barricade fragment from the ork uprising during the Night of Rage" },
  { fr: "Une plaque de matricule d'un véhicule militaire Aztlan datant de la guerre de l'Aztlan", en: "A license plate from an Aztlan military vehicle dating from the Aztlan war" },
  { fr: "Un morceau de panneau 'BIENVENUE À CHICAGO' récupéré avant la création de la Zone de Confinement", en: "A piece of 'WELCOME TO CHICAGO' sign salvaged before the Containment Zone was created" },
  { fr: "Un insigne de sécurité du Renraku Arcology antérieur à la crise de l'IA Deus", en: "A Renraku Arcology security badge from before the Deus AI crisis" },
  { fr: "Un éclat de cristal radiant récupéré lors de la chute de la comète de Halley en 2061", en: "A radiant crystal shard recovered during Halley's Comet's passage in 2061" },
  { fr: "Un tract du Humanis Policlub déchiré en deux, gardé pour ne jamais oublier la haine", en: "A Humanis Policlub pamphlet torn in half, kept to never forget the hatred" },
  { fr: "Un morceau de câble de la grille de Seattle arraché lors du Crash 2.0", en: "A piece of Seattle grid cable torn off during Crash 2.0" },
  { fr: "Un fragment de masque cérémoniel d'un esprit insecte, gardé dans un sac scellé", en: "A fragment of an insect spirit's ceremonial mask, kept in a sealed bag" },
  { fr: "Une carte d'accès au Zurich Orbital annulée, vestige d'une vie antérieure dans la corpo", en: "A voided Zurich Orbital access card, a relic of a former life in the corp" },
  { fr: "Un fragment de la statue de la Liberté répliquée de Neo-Tokyo, tombé lors d'un tremblement de terre", en: "A fragment of the replicated Statue of Liberty from Neo-Tokyo, fallen during an earthquake" },
  { fr: "Un petit drapeau du Tir Tairngire en tissu, froissé et gardé dans une poche intérieure", en: "A small cloth Tir Tairngire flag, crumpled and kept in an inner pocket" },
  { fr: "Un brassard de quarantaine de la zone de Bug City qu'ils n'ont jamais enlevé", en: "A Bug City quarantine armband they never took off" },

  // ——— Cyberpunk lifestyle items ———
  { fr: "Un petit néon flexible qu'ils enroulent autour de leur poignet comme un bracelet lumineux", en: "A small flexible neon strip they coil around their wrist like a glowing bracelet" },
  { fr: "Un patch thermique adhésif qu'ils collent sur leur nuque pour simuler de la fièvre aux scanners corpo", en: "An adhesive thermal patch they stick on their neck to simulate fever on corpo scanners" },
  { fr: "Un filtre à air personnel customisé peint aux couleurs de leur ancien gang", en: "A custom personal air filter painted in their old gang's colors" },
  { fr: "Un stick de maquillage camouflage anti-reconnaissance faciale qu'ils appliquent comme un rituel", en: "A facial-recognition-defeating camo makeup stick they apply as a ritual" },
  { fr: "Un ancien pass VIP du club Dante's Inferno, plastifié et accroché à leur ceinture", en: "An old Dante's Inferno club VIP pass, laminated and clipped to their belt" },
  { fr: "Un petit haut-parleur directionnel qui chuchote des insultes inaudibles vers les caméras de surveillance", en: "A small directional speaker that whispers inaudible insults at surveillance cameras" },
  { fr: "Un bracelet à diodes qui affiche leur alias de runner en morse lumineux", en: "A LED bracelet that displays their runner alias in light-based Morse code" },
  { fr: "Une carte de fidélité d'un stand de ramen des Barrens, presque complète", en: "A loyalty card from a Barrens ramen stand, almost complete" },
  { fr: "Un masque à gaz miniature customisé avec un sourire de clown peint dessus", en: "A custom miniature gas mask with a painted clown smile on it" },
  { fr: "Un hologramme de poche projetant leur propre avis de recherche, gardé par ironie", en: "A pocket hologram projecting their own wanted poster, kept for the irony" },
  { fr: "Un ticket de transport pour le monorail souterrain clandestin de Seattle, périmé", en: "A transit ticket for Seattle's clandestine underground monorail, expired" },
  { fr: "Un petit pot de gel capillaire néon qui brille dans le noir et sent le synthétique", en: "A small pot of neon hair gel that glows in the dark and smells synthetic" },

  // ——— Animal-related items ———
  { fr: "Un collier de chat en cuir trop petit pour tout animal vivant connu", en: "A leather cat collar too small for any known living animal" },
  { fr: "Une plume de corbeau Éveillé trouvée sur le rebord de leur fenêtre chaque matin pendant une semaine", en: "An Awakened raven feather found on their windowsill every morning for a week" },
  { fr: "Un croc de loup-garou monté sur un anneau d'argent, gardé dans un étui en cuir", en: "A werewolf fang mounted on a silver band, kept in a leather case" },
  { fr: "Une écaille de serpent à plumes iridescente qu'ils portent dans leur chapeau", en: "An iridescent feathered serpent scale they keep in their hat" },
  { fr: "Un œuf fossilisé minuscule trouvé dans les tunnels sous Seattle, possiblement Éveillé", en: "A tiny fossilized egg found in the tunnels under Seattle, possibly Awakened" },
  { fr: "Un petit sifflet qui n'attire que les rats, utilisé une seule fois par nécessité", en: "A small whistle that only attracts rats, used once out of necessity" },
  { fr: "Une griffe de griffon montée en broche qui semble plus chaude les jours de pluie", en: "A griffin claw mounted as a brooch that seems warmer on rainy days" },
  { fr: "Un collier GPS désactivé ayant appartenu à un hellhound domestiqué", en: "A deactivated GPS collar that once belonged to a domesticated hellhound" },

  // ——— Music and art related ———
  { fr: "Un médiator en os gravé du logo d'un groupe de goblin rock underground", en: "A bone guitar pick engraved with the logo of an underground goblin rock band" },
  { fr: "Un petit synthétiseur modulaire fait maison qui ne produit qu'un seul son dissonant", en: "A homemade small modular synthesizer that only produces one dissonant sound" },
  { fr: "Un pinceau en poils de licorne que tout le monde soupçonne d'être en nylon", en: "A unicorn hair paintbrush that everyone suspects is just nylon" },
  { fr: "Un fragment de partition musicale griffonné par un compositeur troll célèbre", en: "A fragment of sheet music scrawled by a famous troll composer" },
  { fr: "Un minuscule carnet de croquis rempli de portraits de gens croisés dans le métro de Seattle", en: "A tiny sketchbook filled with portraits of people seen on the Seattle metro" },
  { fr: "Un bâton de craie pastel violet utilisé pour taguer leur symbole avant chaque run", en: "A purple pastel chalk stick used to tag their symbol before every run" },

  // ——— Gambling and games ———
  { fr: "Un jeu de cartes de tarot cyberpunk peint à la main par un oracle aveugle", en: "A hand-painted cyberpunk tarot deck by a blind oracle" },
  { fr: "Une paire de dés en tungstène parfaitement équilibrés, plus lourds qu'ils n'en ont l'air", en: "A pair of perfectly balanced tungsten dice, heavier than they look" },
  { fr: "Un plateau de go magnétique miniature avec une partie en cours depuis trois ans", en: "A miniature magnetic Go board with a game in progress for three years" },
  { fr: "Un jeton de poker holographique qui change de valeur selon l'angle de vue", en: "A holographic poker chip that changes value depending on the viewing angle" },
  { fr: "Un petit damier en ébène et ivoire synthétique qu'ils utilisent pour prendre des décisions tactiques", en: "A small synthetic ebony and ivory checkerboard they use for tactical decisions" },
  { fr: "Un paquet de cartes à jouer où chaque figure a été redessinée en portrait de mégacorpo CEO", en: "A deck of playing cards where every face card has been redrawn as a megacorp CEO portrait" },

  // ——— Documents and papers ———
  { fr: "Un faux passeport si bien fait qu'il est devenu leur seule pièce d'identité", en: "A fake passport so well-made it became their only form of ID" },
  { fr: "Une coupure de journal relatant un accident dont ils sont le seul survivant", en: "A newspaper clipping about an accident they are the sole survivor of" },
  { fr: "Un acte de propriété pour un terrain contaminé dans les Barrens qu'ils gardent par optimisme", en: "A deed for a contaminated lot in the Barrens they keep out of optimism" },
  { fr: "Un carnet de contacts écrit en code, dont ils ont perdu la grille de déchiffrement", en: "A contact book written in code, for which they've lost the cipher key" },
  { fr: "Une carte postale vierge de Tír na nÓg qu'ils n'ont jamais trouvé à qui envoyer", en: "A blank postcard from Tír na nÓg they never found someone to send it to" },
  { fr: "Un certificat de naissance falsifié portant un nom qu'ils préfèrent au leur", en: "A forged birth certificate bearing a name they prefer to their own" },

  // ——— Religious and spiritual items ———
  { fr: "Un chapelet en perles de jais dont chaque grain représente un péché qu'ils n'ont pas commis", en: "A jet bead rosary where each bead represents a sin they haven't committed" },
  { fr: "Un petit bouddha en jade qu'ils frottent avant chaque négociation", en: "A small jade Buddha they rub before every negotiation" },
  { fr: "Une croix en fer forgé bénie par un prêtre de l'Église de la Lumière Éternelle", en: "A wrought iron cross blessed by a priest of the Church of the Eternal Light" },
  { fr: "Un petit sachet d'herbes sacrées amérindiennes noué avec un fil rouge", en: "A small pouch of sacred Amerindian herbs tied with a red string" },
  { fr: "Un mandala de sable miniature scellé sous verre, cadeau d'un moine tibétain", en: "A miniature sand mandala sealed under glass, a gift from a Tibetan monk" },
  { fr: "Un morceau de bois flotté sculpté en forme d'esprit animal par un chamane mourant", en: "A piece of driftwood carved into an animal spirit shape by a dying shaman" },
  { fr: "Un petit encensoir portatif en laiton utilisé pour purifier les zones avant infiltration", en: "A small portable brass censer used to purify areas before infiltration" },
];
